import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/00-foundations/"
  },
  {
    "text": "Start Here",
    "link": "/00-foundations/start-here/"
  },
  {
    "text": "How the Web Works Map",
    "link": "/00-foundations/how-the-web-works-map/"
  },
  {
    "text": "How to Read This Handbook",
    "link": "/00-foundations/how-to-read-this-handbook/"
  },
  {
    "text": "Prerequisites Checklist",
    "link": "/00-foundations/prerequisites-checklist/"
  },
  {
    "text": "Conventions Used",
    "link": "/00-foundations/conventions-used/"
  }
]
