import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/01-computer-science/"
  },
  {
    "text": "Binary",
    "link": "/01-computer-science/binary/"
  },
  {
    "text": "Bits and Bytes",
    "link": "/01-computer-science/bits-and-bytes/"
  },
  {
    "text": "CPU",
    "link": "/01-computer-science/cpu/"
  },
  {
    "text": "Memory",
    "link": "/01-computer-science/memory/"
  },
  {
    "text": "Stack",
    "link": "/01-computer-science/stack/"
  },
  {
    "text": "Heap",
    "link": "/01-computer-science/heap/"
  },
  {
    "text": "Process",
    "link": "/01-computer-science/process/"
  },
  {
    "text": "Thread",
    "link": "/01-computer-science/thread/"
  },
  {
    "text": "Event Loop (Runtime View)",
    "link": "/01-computer-science/event-loop-cs/"
  },
  {
    "text": "Compiler",
    "link": "/01-computer-science/compiler/"
  },
  {
    "text": "Interpreter",
    "link": "/01-computer-science/interpreter/"
  },
  {
    "text": "Runtime",
    "link": "/01-computer-science/runtime/"
  },
  {
    "text": "Garbage Collection",
    "link": "/01-computer-science/garbage-collection/"
  },
  {
    "text": "Time Complexity",
    "link": "/01-computer-science/time-complexity/"
  },
  {
    "text": "Space Complexity",
    "link": "/01-computer-science/space-complexity/"
  },
  {
    "text": "Big O",
    "link": "/01-computer-science/big-o/"
  },
  {
    "text": "Data Structures",
    "collapsed": true,
    "items": [
      {
        "text": "Overview",
        "link": "/01-computer-science/data-structures/"
      },
      {
        "text": "Array",
        "link": "/01-computer-science/data-structures/array/"
      },
      {
        "text": "Linked List",
        "link": "/01-computer-science/data-structures/linked-list/"
      },
      {
        "text": "Stack (Data Structure)",
        "link": "/01-computer-science/data-structures/stack-ds/"
      },
      {
        "text": "Queue",
        "link": "/01-computer-science/data-structures/queue/"
      },
      {
        "text": "Hash Table",
        "link": "/01-computer-science/data-structures/hash-table/"
      },
      {
        "text": "Tree",
        "link": "/01-computer-science/data-structures/tree/"
      },
      {
        "text": "Graph",
        "link": "/01-computer-science/data-structures/graph/"
      }
    ]
  },
  {
    "text": "Algorithms",
    "collapsed": true,
    "items": [
      {
        "text": "Overview",
        "link": "/01-computer-science/algorithms/"
      },
      {
        "text": "Searching",
        "link": "/01-computer-science/algorithms/searching/"
      },
      {
        "text": "Sorting",
        "link": "/01-computer-science/algorithms/sorting/"
      },
      {
        "text": "Recursion",
        "link": "/01-computer-science/algorithms/recursion/"
      },
      {
        "text": "Dynamic Programming Intro",
        "link": "/01-computer-science/algorithms/dynamic-programming-intro/"
      }
    ]
  }
]
