import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/02-internet/"
  },
  {
    "text": "What is the Internet",
    "link": "/02-internet/what-is-the-internet/"
  },
  {
    "text": "Client",
    "link": "/02-internet/client/"
  },
  {
    "text": "Server",
    "link": "/02-internet/server/"
  },
  {
    "text": "ISP",
    "link": "/02-internet/isp/"
  },
  {
    "text": "Router",
    "link": "/02-internet/router/"
  },
  {
    "text": "Switch",
    "link": "/02-internet/switch/"
  },
  {
    "text": "DNS",
    "link": "/02-internet/dns/"
  },
  {
    "text": "Domain",
    "link": "/02-internet/domain/"
  },
  {
    "text": "IP",
    "link": "/02-internet/ip/"
  },
  {
    "text": "IPv4",
    "link": "/02-internet/ipv4/"
  },
  {
    "text": "IPv6",
    "link": "/02-internet/ipv6/"
  },
  {
    "text": "TCP",
    "link": "/02-internet/tcp/"
  },
  {
    "text": "UDP",
    "link": "/02-internet/udp/"
  },
  {
    "text": "HTTP",
    "link": "/02-internet/http/"
  },
  {
    "text": "HTTPS",
    "link": "/02-internet/https/"
  },
  {
    "text": "SSL",
    "link": "/02-internet/ssl/"
  },
  {
    "text": "TLS",
    "link": "/02-internet/tls/"
  },
  {
    "text": "SSH",
    "link": "/02-internet/ssh/"
  },
  {
    "text": "WebSocket",
    "link": "/02-internet/websocket/"
  },
  {
    "text": "Server-Sent Events",
    "link": "/02-internet/sse/"
  },
  {
    "text": "HTTP/2",
    "link": "/02-internet/http2/"
  },
  {
    "text": "HTTP/3",
    "link": "/02-internet/http3/"
  },
  {
    "text": "QUIC",
    "link": "/02-internet/quic/"
  },
  {
    "text": "Cookies",
    "link": "/02-internet/cookies/"
  },
  {
    "text": "Sessions",
    "link": "/02-internet/sessions/"
  },
  {
    "text": "Authentication",
    "link": "/02-internet/authentication/"
  },
  {
    "text": "Authorization",
    "link": "/02-internet/authorization/"
  },
  {
    "text": "REST",
    "link": "/02-internet/rest/"
  },
  {
    "text": "GraphQL",
    "link": "/02-internet/graphql/"
  },
  {
    "text": "HTTP Caching",
    "link": "/02-internet/http-caching/"
  },
  {
    "text": "CDN Basics",
    "link": "/02-internet/cdn-basics/"
  },
  {
    "text": "Load Balancing Basics",
    "link": "/02-internet/load-balancing-basics/"
  }
]
