import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/03-browser/"
  },
  {
    "text": "Browser Architecture",
    "link": "/03-browser/browser-architecture/"
  },
  {
    "text": "Multi-Process Model",
    "link": "/03-browser/multi-process-model/"
  },
  {
    "text": "Rendering Engine",
    "link": "/03-browser/rendering-engine/"
  },
  {
    "text": "JavaScript Engine",
    "link": "/03-browser/javascript-engine/"
  },
  {
    "text": "V8",
    "link": "/03-browser/v8/"
  },
  {
    "text": "SpiderMonkey",
    "link": "/03-browser/spidermonkey/"
  },
  {
    "text": "JavaScriptCore",
    "link": "/03-browser/javascriptcore/"
  },
  {
    "text": "Parsing HTML",
    "link": "/03-browser/parsing-html/"
  },
  {
    "text": "Parsing CSS",
    "link": "/03-browser/parsing-css/"
  },
  {
    "text": "DOM",
    "link": "/03-browser/dom/"
  },
  {
    "text": "CSSOM",
    "link": "/03-browser/cssom/"
  },
  {
    "text": "Render Tree",
    "link": "/03-browser/render-tree/"
  },
  {
    "text": "Layout",
    "link": "/03-browser/layout/"
  },
  {
    "text": "Paint",
    "link": "/03-browser/paint/"
  },
  {
    "text": "Composite",
    "link": "/03-browser/composite/"
  },
  {
    "text": "GPU",
    "link": "/03-browser/gpu/"
  },
  {
    "text": "Reflow",
    "link": "/03-browser/reflow/"
  },
  {
    "text": "Repaint",
    "link": "/03-browser/repaint/"
  },
  {
    "text": "Critical Rendering Path",
    "link": "/03-browser/critical-rendering-path/"
  },
  {
    "text": "Call Stack",
    "link": "/03-browser/call-stack/"
  },
  {
    "text": "Task Queue",
    "link": "/03-browser/task-queue/"
  },
  {
    "text": "Event Loop",
    "link": "/03-browser/event-loop/"
  },
  {
    "text": "Microtasks",
    "link": "/03-browser/microtasks/"
  },
  {
    "text": "Macrotasks",
    "link": "/03-browser/macrotasks/"
  },
  {
    "text": "Memory Management",
    "link": "/03-browser/memory-management/"
  },
  {
    "text": "Garbage Collection in the Browser",
    "link": "/03-browser/garbage-collection-browser/"
  },
  {
    "text": "DevTools Rendering Panel",
    "link": "/03-browser/devtools-rendering-panel/"
  }
]
