import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/04-html/"
  },
  {
    "text": "Semantic HTML",
    "link": "/04-html/semantic-html/"
  },
  {
    "text": "Document Structure",
    "link": "/04-html/document-structure/"
  },
  {
    "text": "Forms",
    "link": "/04-html/forms/"
  },
  {
    "text": "Media Elements",
    "link": "/04-html/media-elements/"
  },
  {
    "text": "Metadata",
    "link": "/04-html/metadata/"
  },
  {
    "text": "SEO Basics",
    "link": "/04-html/seo-basics/"
  },
  {
    "text": "Scripts",
    "link": "/04-html/scripts/"
  },
  {
    "text": "defer",
    "link": "/04-html/defer/"
  },
  {
    "text": "async",
    "link": "/04-html/async/"
  },
  {
    "text": "Module Scripts",
    "link": "/04-html/module-scripts/"
  },
  {
    "text": "preload",
    "link": "/04-html/preload/"
  },
  {
    "text": "prefetch",
    "link": "/04-html/prefetch/"
  },
  {
    "text": "preconnect",
    "link": "/04-html/preconnect/"
  },
  {
    "text": "modulepreload",
    "link": "/04-html/modulepreload/"
  },
  {
    "text": "Templates and Slots",
    "link": "/04-html/templates-and-slots/"
  }
]
