import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/05-css/"
  },
  {
    "text": "Cascade",
    "link": "/05-css/cascade/"
  },
  {
    "text": "Specificity",
    "link": "/05-css/specificity/"
  },
  {
    "text": "Inheritance",
    "link": "/05-css/inheritance/"
  },
  {
    "text": "Box Model",
    "link": "/05-css/box-model/"
  },
  {
    "text": "Positioning",
    "link": "/05-css/positioning/"
  },
  {
    "text": "Flexbox",
    "link": "/05-css/flexbox/"
  },
  {
    "text": "Grid",
    "link": "/05-css/grid/"
  },
  {
    "text": "Responsive Design",
    "link": "/05-css/responsive-design/"
  },
  {
    "text": "Media Queries",
    "link": "/05-css/media-queries/"
  },
  {
    "text": "Container Queries",
    "link": "/05-css/container-queries/"
  },
  {
    "text": "Animations",
    "link": "/05-css/animations/"
  },
  {
    "text": "Transitions",
    "link": "/05-css/transitions/"
  },
  {
    "text": "Transforms",
    "link": "/05-css/transforms/"
  },
  {
    "text": "Compositing",
    "link": "/05-css/compositing/"
  },
  {
    "text": "Containment",
    "link": "/05-css/containment/"
  },
  {
    "text": "Layers",
    "link": "/05-css/layers/"
  },
  {
    "text": "Modern CSS",
    "link": "/05-css/modern-css/"
  },
  {
    "text": "CSS Architecture",
    "link": "/05-css/css-architecture/"
  }
]
