import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/06-javascript/"
  },
  {
    "text": "Variables",
    "link": "/06-javascript/variables/"
  },
  {
    "text": "Types and Values",
    "link": "/06-javascript/types-and-values/"
  },
  {
    "text": "Scope",
    "link": "/06-javascript/scope/"
  },
  {
    "text": "Closures",
    "link": "/06-javascript/closures/"
  },
  {
    "text": "Hoisting",
    "link": "/06-javascript/hoisting/"
  },
  {
    "text": "Execution Context",
    "link": "/06-javascript/execution-context/"
  },
  {
    "text": "Lexical Environment",
    "link": "/06-javascript/lexical-environment/"
  },
  {
    "text": "Prototype",
    "link": "/06-javascript/prototype/"
  },
  {
    "text": "Prototype Chain",
    "link": "/06-javascript/prototype-chain/"
  },
  {
    "text": "this",
    "link": "/06-javascript/this/"
  },
  {
    "text": "Classes",
    "link": "/06-javascript/classes/"
  },
  {
    "text": "Functions",
    "link": "/06-javascript/functions/"
  },
  {
    "text": "Objects",
    "link": "/06-javascript/objects/"
  },
  {
    "text": "Arrays",
    "link": "/06-javascript/arrays/"
  },
  {
    "text": "Modules",
    "link": "/06-javascript/modules/"
  },
  {
    "text": "ES Modules",
    "link": "/06-javascript/es-modules/"
  },
  {
    "text": "CommonJS",
    "link": "/06-javascript/commonjs/"
  },
  {
    "text": "Async Programming",
    "link": "/06-javascript/async-programming/"
  },
  {
    "text": "Event Loop (JavaScript View)",
    "link": "/06-javascript/event-loop-js/"
  },
  {
    "text": "Promise",
    "link": "/06-javascript/promise/"
  },
  {
    "text": "Async/Await",
    "link": "/06-javascript/async-await/"
  },
  {
    "text": "Generator",
    "link": "/06-javascript/generator/"
  },
  {
    "text": "Iterator",
    "link": "/06-javascript/iterator/"
  },
  {
    "text": "Fetch API",
    "link": "/06-javascript/fetch-api/"
  },
  {
    "text": "AbortController",
    "link": "/06-javascript/abortcontroller/"
  },
  {
    "text": "Proxy",
    "link": "/06-javascript/proxy/"
  },
  {
    "text": "Reflect",
    "link": "/06-javascript/reflect/"
  },
  {
    "text": "Symbols",
    "link": "/06-javascript/symbols/"
  },
  {
    "text": "WeakMap",
    "link": "/06-javascript/weakmap/"
  },
  {
    "text": "WeakSet",
    "link": "/06-javascript/weakset/"
  },
  {
    "text": "Error Handling",
    "link": "/06-javascript/error-handling/"
  },
  {
    "text": "Strict Mode",
    "link": "/06-javascript/strict-mode/"
  },
  {
    "text": "Memory and References",
    "link": "/06-javascript/memory-and-references/"
  }
]
