import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/07-typescript/"
  },
  {
    "text": "Types",
    "link": "/07-typescript/types/"
  },
  {
    "text": "Interfaces",
    "link": "/07-typescript/interfaces/"
  },
  {
    "text": "Type vs Interface",
    "link": "/07-typescript/type-vs-interface/"
  },
  {
    "text": "Generics",
    "link": "/07-typescript/generics/"
  },
  {
    "text": "Utility Types",
    "link": "/07-typescript/utility-types/"
  },
  {
    "text": "Type Inference",
    "link": "/07-typescript/type-inference/"
  },
  {
    "text": "Advanced Types",
    "link": "/07-typescript/advanced-types/"
  },
  {
    "text": "Declaration Files",
    "link": "/07-typescript/declaration-files/"
  },
  {
    "text": "tsconfig",
    "link": "/07-typescript/tsconfig/"
  },
  {
    "text": "TypeScript Compiler",
    "link": "/07-typescript/compiler/"
  },
  {
    "text": "Type Narrowing",
    "link": "/07-typescript/type-narrowing/"
  },
  {
    "text": "satisfies",
    "link": "/07-typescript/satisfies/"
  },
  {
    "text": "Enums and Alternatives",
    "link": "/07-typescript/enums-and-alternatives/"
  },
  {
    "text": "TypeScript with React",
    "link": "/07-typescript/typescript-with-react/"
  }
]
