import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/08-jsx-and-react-runtime/"
  },
  {
    "text": "JSX",
    "link": "/08-jsx-and-react-runtime/jsx/"
  },
  {
    "text": "Babel",
    "link": "/08-jsx-and-react-runtime/babel/"
  },
  {
    "text": "AST",
    "link": "/08-jsx-and-react-runtime/ast/"
  },
  {
    "text": "JSX Transform",
    "link": "/08-jsx-and-react-runtime/jsx-transform/"
  },
  {
    "text": "React.createElement",
    "link": "/08-jsx-and-react-runtime/react-createelement/"
  },
  {
    "text": "Virtual DOM",
    "link": "/08-jsx-and-react-runtime/virtual-dom/"
  },
  {
    "text": "Fiber",
    "link": "/08-jsx-and-react-runtime/fiber/"
  },
  {
    "text": "Reconciliation",
    "link": "/08-jsx-and-react-runtime/reconciliation/"
  },
  {
    "text": "Diffing Algorithm",
    "link": "/08-jsx-and-react-runtime/diffing-algorithm/"
  },
  {
    "text": "Keys",
    "link": "/08-jsx-and-react-runtime/keys/"
  },
  {
    "text": "Fragments",
    "link": "/08-jsx-and-react-runtime/fragments/"
  }
]
