import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/09-browser-apis/"
  },
  {
    "text": "localStorage",
    "link": "/09-browser-apis/localstorage/"
  },
  {
    "text": "sessionStorage",
    "link": "/09-browser-apis/sessionstorage/"
  },
  {
    "text": "IndexedDB",
    "link": "/09-browser-apis/indexeddb/"
  },
  {
    "text": "Cache Storage",
    "link": "/09-browser-apis/cache-storage/"
  },
  {
    "text": "History API",
    "link": "/09-browser-apis/history-api/"
  },
  {
    "text": "Clipboard API",
    "link": "/09-browser-apis/clipboard-api/"
  },
  {
    "text": "Intersection Observer",
    "link": "/09-browser-apis/intersection-observer/"
  },
  {
    "text": "Mutation Observer",
    "link": "/09-browser-apis/mutation-observer/"
  },
  {
    "text": "Resize Observer",
    "link": "/09-browser-apis/resize-observer/"
  },
  {
    "text": "Broadcast Channel",
    "link": "/09-browser-apis/broadcast-channel/"
  },
  {
    "text": "Web Workers",
    "link": "/09-browser-apis/web-workers/"
  },
  {
    "text": "Service Workers",
    "link": "/09-browser-apis/service-workers/"
  },
  {
    "text": "Notifications",
    "link": "/09-browser-apis/notifications/"
  },
  {
    "text": "Geolocation",
    "link": "/09-browser-apis/geolocation/"
  },
  {
    "text": "WebSocket API",
    "link": "/09-browser-apis/web-sockets-api/"
  },
  {
    "text": "Streams API",
    "link": "/09-browser-apis/streams-api/"
  },
  {
    "text": "File API",
    "link": "/09-browser-apis/file-api/"
  },
  {
    "text": "Web Components",
    "link": "/09-browser-apis/web-components/"
  },
  {
    "text": "Custom Elements",
    "link": "/09-browser-apis/custom-elements/"
  },
  {
    "text": "Shadow DOM",
    "link": "/09-browser-apis/shadow-dom/"
  }
]
