import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/10-react/"
  },
  {
    "text": "React Philosophy",
    "link": "/10-react/philosophy/"
  },
  {
    "text": "Components",
    "link": "/10-react/components/"
  },
  {
    "text": "Props",
    "link": "/10-react/props/"
  },
  {
    "text": "State",
    "link": "/10-react/state/"
  },
  {
    "text": "Hooks",
    "link": "/10-react/hooks/"
  },
  {
    "text": "Rules of Hooks",
    "link": "/10-react/rules-of-hooks/"
  },
  {
    "text": "Context",
    "link": "/10-react/context/"
  },
  {
    "text": "Reducer",
    "link": "/10-react/reducer/"
  },
  {
    "text": "Memoization in React",
    "link": "/10-react/memoization/"
  },
  {
    "text": "React.memo",
    "link": "/10-react/react-memo/"
  },
  {
    "text": "useMemo",
    "link": "/10-react/usememo/"
  },
  {
    "text": "useCallback",
    "link": "/10-react/usecallback/"
  },
  {
    "text": "useRef",
    "link": "/10-react/useref/"
  },
  {
    "text": "useEffect",
    "link": "/10-react/useeffect/"
  },
  {
    "text": "useLayoutEffect",
    "link": "/10-react/uselayouteffect/"
  },
  {
    "text": "useImperativeHandle",
    "link": "/10-react/useimperativehandle/"
  },
  {
    "text": "useId",
    "link": "/10-react/useid/"
  },
  {
    "text": "use",
    "link": "/10-react/use/"
  },
  {
    "text": "Suspense",
    "link": "/10-react/suspense/"
  },
  {
    "text": "Lazy Loading",
    "link": "/10-react/lazy-loading/"
  },
  {
    "text": "Error Boundaries",
    "link": "/10-react/error-boundaries/"
  },
  {
    "text": "Portals",
    "link": "/10-react/portals/"
  },
  {
    "text": "Concurrent Rendering",
    "link": "/10-react/concurrent-rendering/"
  },
  {
    "text": "Transitions",
    "link": "/10-react/transitions/"
  },
  {
    "text": "useDeferredValue",
    "link": "/10-react/deferred-value/"
  },
  {
    "text": "Strict Mode",
    "link": "/10-react/strict-mode/"
  },
  {
    "text": "React Compiler",
    "link": "/10-react/react-compiler/"
  },
  {
    "text": "Server Components Overview",
    "link": "/10-react/server-components-overview/"
  },
  {
    "text": "Effects vs Events",
    "link": "/10-react/effects-vs-events/"
  }
]
