import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/11-nextjs/"
  },
  {
    "text": "App Router",
    "link": "/11-nextjs/app-router/"
  },
  {
    "text": "Pages Router",
    "link": "/11-nextjs/pages-router/"
  },
  {
    "text": "Routing",
    "link": "/11-nextjs/routing/"
  },
  {
    "text": "Layouts",
    "link": "/11-nextjs/layouts/"
  },
  {
    "text": "Nested Layouts",
    "link": "/11-nextjs/nested-layouts/"
  },
  {
    "text": "Templates",
    "link": "/11-nextjs/templates/"
  },
  {
    "text": "Loading UI",
    "link": "/11-nextjs/loading-ui/"
  },
  {
    "text": "Error UI",
    "link": "/11-nextjs/error-ui/"
  },
  {
    "text": "Metadata",
    "link": "/11-nextjs/metadata/"
  },
  {
    "text": "Route Handlers",
    "link": "/11-nextjs/route-handlers/"
  },
  {
    "text": "Middleware",
    "link": "/11-nextjs/middleware/"
  },
  {
    "text": "Edge Runtime",
    "link": "/11-nextjs/edge-runtime/"
  },
  {
    "text": "Node Runtime",
    "link": "/11-nextjs/node-runtime/"
  },
  {
    "text": "Image Optimization",
    "link": "/11-nextjs/image-optimization/"
  },
  {
    "text": "Fonts",
    "link": "/11-nextjs/fonts/"
  },
  {
    "text": "Server Components",
    "link": "/11-nextjs/server-components/"
  },
  {
    "text": "Client Components",
    "link": "/11-nextjs/client-components/"
  },
  {
    "text": "Server Actions",
    "link": "/11-nextjs/server-actions/"
  },
  {
    "text": "Streaming",
    "link": "/11-nextjs/streaming/"
  },
  {
    "text": "Caching",
    "link": "/11-nextjs/caching/"
  },
  {
    "text": "Partial Prerendering",
    "link": "/11-nextjs/partial-prerendering/"
  },
  {
    "text": "Data Fetching",
    "link": "/11-nextjs/data-fetching/"
  },
  {
    "text": "Route Groups",
    "link": "/11-nextjs/route-groups/"
  },
  {
    "text": "Intercepting Routes",
    "link": "/11-nextjs/intercepting-routes/"
  },
  {
    "text": "Parallel Routes",
    "link": "/11-nextjs/parallel-routes/"
  }
]
