import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/12-rendering/"
  },
  {
    "text": "Client-Side Rendering",
    "link": "/12-rendering/csr/"
  },
  {
    "text": "Server-Side Rendering",
    "link": "/12-rendering/ssr/"
  },
  {
    "text": "Static Site Generation",
    "link": "/12-rendering/ssg/"
  },
  {
    "text": "Incremental Static Regeneration",
    "link": "/12-rendering/isr/"
  },
  {
    "text": "Partial Prerendering",
    "link": "/12-rendering/ppr/"
  },
  {
    "text": "Streaming",
    "link": "/12-rendering/streaming/"
  },
  {
    "text": "Hydration",
    "link": "/12-rendering/hydration/"
  },
  {
    "text": "Progressive Hydration",
    "link": "/12-rendering/progressive-hydration/"
  },
  {
    "text": "Resumability",
    "link": "/12-rendering/resumability/"
  },
  {
    "text": "Edge Rendering",
    "link": "/12-rendering/edge-rendering/"
  },
  {
    "text": "CDN",
    "link": "/12-rendering/cdn/"
  },
  {
    "text": "Browser Cache",
    "link": "/12-rendering/browser-cache/"
  },
  {
    "text": "Cache-Control",
    "link": "/12-rendering/cache-control/"
  },
  {
    "text": "ETag",
    "link": "/12-rendering/etag/"
  },
  {
    "text": "Stale While Revalidate",
    "link": "/12-rendering/stale-while-revalidate/"
  },
  {
    "text": "Rendering Strategy Decision Tree",
    "link": "/12-rendering/rendering-strategy-decision-tree/"
  }
]
