import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/13-performance/"
  },
  {
    "text": "Bundle",
    "link": "/13-performance/bundle/"
  },
  {
    "text": "Chunk",
    "link": "/13-performance/chunk/"
  },
  {
    "text": "Bundling",
    "link": "/13-performance/bundling/"
  },
  {
    "text": "Code Splitting",
    "link": "/13-performance/code-splitting/"
  },
  {
    "text": "Tree Shaking",
    "link": "/13-performance/tree-shaking/"
  },
  {
    "text": "Dead Code Elimination",
    "link": "/13-performance/dead-code-elimination/"
  },
  {
    "text": "Dynamic Import",
    "link": "/13-performance/dynamic-import/"
  },
  {
    "text": "Lazy Loading",
    "link": "/13-performance/lazy-loading/"
  },
  {
    "text": "Debounce",
    "link": "/13-performance/debounce/"
  },
  {
    "text": "Throttle",
    "link": "/13-performance/throttle/"
  },
  {
    "text": "Memoization",
    "link": "/13-performance/memoization-perf/"
  },
  {
    "text": "Virtualization",
    "link": "/13-performance/virtualization/"
  },
  {
    "text": "Image Optimization",
    "link": "/13-performance/image-optimization-perf/"
  },
  {
    "text": "Font Performance",
    "link": "/13-performance/font-performance/"
  },
  {
    "text": "Lighthouse",
    "link": "/13-performance/lighthouse/"
  },
  {
    "text": "Core Web Vitals",
    "link": "/13-performance/core-web-vitals/"
  },
  {
    "text": "LCP",
    "link": "/13-performance/lcp/"
  },
  {
    "text": "CLS",
    "link": "/13-performance/cls/"
  },
  {
    "text": "INP",
    "link": "/13-performance/inp/"
  },
  {
    "text": "TTFB",
    "link": "/13-performance/ttfb/"
  },
  {
    "text": "TTI",
    "link": "/13-performance/tti/"
  },
  {
    "text": "FCP",
    "link": "/13-performance/fcp/"
  },
  {
    "text": "TBT",
    "link": "/13-performance/tbt/"
  },
  {
    "text": "Profiling",
    "link": "/13-performance/profiling/"
  },
  {
    "text": "Long Tasks",
    "link": "/13-performance/long-tasks/"
  },
  {
    "text": "Scheduler and Yielding",
    "link": "/13-performance/scheduler-yielding/"
  }
]
