import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/14-build-tools/"
  },
  {
    "text": "Node.js",
    "link": "/14-build-tools/nodejs/"
  },
  {
    "text": "npm",
    "link": "/14-build-tools/npm/"
  },
  {
    "text": "pnpm",
    "link": "/14-build-tools/pnpm/"
  },
  {
    "text": "Yarn",
    "link": "/14-build-tools/yarn/"
  },
  {
    "text": "Bun",
    "link": "/14-build-tools/bun/"
  },
  {
    "text": "Module Resolution",
    "link": "/14-build-tools/module-resolution/"
  },
  {
    "text": "Webpack",
    "link": "/14-build-tools/webpack/"
  },
  {
    "text": "Rollup",
    "link": "/14-build-tools/rollup/"
  },
  {
    "text": "Vite",
    "link": "/14-build-tools/vite/"
  },
  {
    "text": "Turbopack",
    "link": "/14-build-tools/turbopack/"
  },
  {
    "text": "Rspack",
    "link": "/14-build-tools/rspack/"
  },
  {
    "text": "Parcel",
    "link": "/14-build-tools/parcel/"
  },
  {
    "text": "Babel",
    "link": "/14-build-tools/babel/"
  },
  {
    "text": "SWC",
    "link": "/14-build-tools/swc/"
  },
  {
    "text": "esbuild",
    "link": "/14-build-tools/esbuild/"
  },
  {
    "text": "PostCSS",
    "link": "/14-build-tools/postcss/"
  },
  {
    "text": "Source Maps",
    "link": "/14-build-tools/source-maps/"
  },
  {
    "text": "Monorepo Tooling",
    "link": "/14-build-tools/monorepo-tooling/"
  }
]
