import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/15-architecture/"
  },
  {
    "text": "Feature-Based Architecture",
    "link": "/15-architecture/feature-based-architecture/"
  },
  {
    "text": "Atomic Design",
    "link": "/15-architecture/atomic-design/"
  },
  {
    "text": "Design Systems",
    "link": "/15-architecture/design-systems/"
  },
  {
    "text": "Monorepo",
    "link": "/15-architecture/monorepo/"
  },
  {
    "text": "Micro Frontends",
    "link": "/15-architecture/micro-frontends/"
  },
  {
    "text": "Module Federation",
    "link": "/15-architecture/module-federation/"
  },
  {
    "text": "State Management",
    "link": "/15-architecture/state-management/"
  },
  {
    "text": "Redux",
    "link": "/15-architecture/redux/"
  },
  {
    "text": "Zustand",
    "link": "/15-architecture/zustand/"
  },
  {
    "text": "Jotai",
    "link": "/15-architecture/jotai/"
  },
  {
    "text": "TanStack Query",
    "link": "/15-architecture/tanstack-query/"
  },
  {
    "text": "React Router",
    "link": "/15-architecture/react-router/"
  },
  {
    "text": "URL as State",
    "link": "/15-architecture/url-as-state/"
  },
  {
    "text": "Component Libraries",
    "link": "/15-architecture/component-libraries/"
  },
  {
    "text": "API Layer Design",
    "link": "/15-architecture/api-layer-design/"
  },
  {
    "text": "Error Handling Architecture",
    "link": "/15-architecture/error-handling-architecture/"
  }
]
