import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/16-testing/"
  },
  {
    "text": "Testing Pyramid",
    "link": "/16-testing/testing-pyramid/"
  },
  {
    "text": "Unit Testing",
    "link": "/16-testing/unit-testing/"
  },
  {
    "text": "Integration Testing",
    "link": "/16-testing/integration-testing/"
  },
  {
    "text": "E2E Testing",
    "link": "/16-testing/e2e-testing/"
  },
  {
    "text": "Jest",
    "link": "/16-testing/jest/"
  },
  {
    "text": "Vitest",
    "link": "/16-testing/vitest/"
  },
  {
    "text": "React Testing Library",
    "link": "/16-testing/react-testing-library/"
  },
  {
    "text": "Cypress",
    "link": "/16-testing/cypress/"
  },
  {
    "text": "Playwright",
    "link": "/16-testing/playwright/"
  },
  {
    "text": "Mocking",
    "link": "/16-testing/mocking/"
  },
  {
    "text": "Spying",
    "link": "/16-testing/spying/"
  },
  {
    "text": "MSW",
    "link": "/16-testing/msw/"
  },
  {
    "text": "Visual Regression",
    "link": "/16-testing/visual-regression/"
  },
  {
    "text": "Accessibility Testing",
    "link": "/16-testing/accessibility-testing/"
  },
  {
    "text": "Test Strategy",
    "link": "/16-testing/test-strategy/"
  }
]
