import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/17-security/"
  },
  {
    "text": "Threat Model",
    "link": "/17-security/threat-model/"
  },
  {
    "text": "XSS",
    "link": "/17-security/xss/"
  },
  {
    "text": "CSRF",
    "link": "/17-security/csrf/"
  },
  {
    "text": "CORS",
    "link": "/17-security/cors/"
  },
  {
    "text": "Content Security Policy",
    "link": "/17-security/csp/"
  },
  {
    "text": "JWT",
    "link": "/17-security/jwt/"
  },
  {
    "text": "OAuth",
    "link": "/17-security/oauth/"
  },
  {
    "text": "OIDC",
    "link": "/17-security/oidc/"
  },
  {
    "text": "Cookies Security",
    "link": "/17-security/cookies-security/"
  },
  {
    "text": "SameSite",
    "link": "/17-security/samesite/"
  },
  {
    "text": "Secure Cookies",
    "link": "/17-security/secure-cookies/"
  },
  {
    "text": "HTTPS Security",
    "link": "/17-security/https-security/"
  },
  {
    "text": "Clickjacking",
    "link": "/17-security/clickjacking/"
  },
  {
    "text": "Prototype Pollution",
    "link": "/17-security/prototype-pollution/"
  },
  {
    "text": "Supply Chain Security",
    "link": "/17-security/supply-chain-security/"
  },
  {
    "text": "Secrets in the Frontend",
    "link": "/17-security/secrets-in-frontend/"
  }
]
