import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/18-accessibility/"
  },
  {
    "text": "Why Accessibility",
    "link": "/18-accessibility/why-accessibility/"
  },
  {
    "text": "WCAG",
    "link": "/18-accessibility/wcag/"
  },
  {
    "text": "ARIA",
    "link": "/18-accessibility/aria/"
  },
  {
    "text": "Semantic HTML for Accessibility",
    "link": "/18-accessibility/semantic-html-a11y/"
  },
  {
    "text": "Keyboard Navigation",
    "link": "/18-accessibility/keyboard-navigation/"
  },
  {
    "text": "Focus Management",
    "link": "/18-accessibility/focus-management/"
  },
  {
    "text": "Screen Readers",
    "link": "/18-accessibility/screen-readers/"
  },
  {
    "text": "Color and Contrast",
    "link": "/18-accessibility/color-and-contrast/"
  },
  {
    "text": "Accessible Forms",
    "link": "/18-accessibility/forms-a11y/"
  },
  {
    "text": "Live Regions",
    "link": "/18-accessibility/live-regions/"
  },
  {
    "text": "Accessible Components",
    "link": "/18-accessibility/accessible-components/"
  },
  {
    "text": "Accessibility Testing",
    "link": "/18-accessibility/a11y-testing/"
  },
  {
    "text": "Accessibility in React",
    "link": "/18-accessibility/a11y-in-react/"
  },
  {
    "text": "Accessibility in Next.js",
    "link": "/18-accessibility/a11y-in-nextjs/"
  }
]
