import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/19-deployment/"
  },
  {
    "text": "Docker",
    "link": "/19-deployment/docker/"
  },
  {
    "text": "Nginx",
    "link": "/19-deployment/nginx/"
  },
  {
    "text": "Reverse Proxy",
    "link": "/19-deployment/reverse-proxy/"
  },
  {
    "text": "CDN Deployment",
    "link": "/19-deployment/cdn-deployment/"
  },
  {
    "text": "CI/CD",
    "link": "/19-deployment/ci-cd/"
  },
  {
    "text": "GitHub Actions",
    "link": "/19-deployment/github-actions/"
  },
  {
    "text": "Vercel",
    "link": "/19-deployment/vercel/"
  },
  {
    "text": "Netlify",
    "link": "/19-deployment/netlify/"
  },
  {
    "text": "AWS for Frontend",
    "link": "/19-deployment/aws-frontend/"
  },
  {
    "text": "Cloudflare",
    "link": "/19-deployment/cloudflare/"
  },
  {
    "text": "Environment Config",
    "link": "/19-deployment/environment-config/"
  },
  {
    "text": "Preview Deployments",
    "link": "/19-deployment/preview-deployments/"
  },
  {
    "text": "Rollback Strategies",
    "link": "/19-deployment/rollback-strategies/"
  }
]
