import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/20-observability/"
  },
  {
    "text": "Chrome DevTools",
    "link": "/20-observability/chrome-devtools/"
  },
  {
    "text": "Debugging JavaScript",
    "link": "/20-observability/debugging-javascript/"
  },
  {
    "text": "Debugging Network",
    "link": "/20-observability/debugging-network/"
  },
  {
    "text": "Debugging Performance",
    "link": "/20-observability/debugging-performance/"
  },
  {
    "text": "Source Maps Debugging",
    "link": "/20-observability/source-maps-debugging/"
  },
  {
    "text": "Logging",
    "link": "/20-observability/logging/"
  },
  {
    "text": "Error Tracking",
    "link": "/20-observability/error-tracking/"
  },
  {
    "text": "Real User Monitoring",
    "link": "/20-observability/rum/"
  },
  {
    "text": "Web Vitals Monitoring",
    "link": "/20-observability/web-vitals-monitoring/"
  },
  {
    "text": "Frontend Tracing",
    "link": "/20-observability/tracing-frontend/"
  },
  {
    "text": "Feature Telemetry",
    "link": "/20-observability/feature-telemetry/"
  }
]
