import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/21-frontend-system-design/"
  },
  {
    "text": "Scaling React Applications",
    "link": "/21-frontend-system-design/scaling-react-applications/"
  },
  {
    "text": "Caching Strategies",
    "link": "/21-frontend-system-design/caching-strategies/"
  },
  {
    "text": "Optimistic UI",
    "link": "/21-frontend-system-design/optimistic-ui/"
  },
  {
    "text": "Offline First",
    "link": "/21-frontend-system-design/offline-first/"
  },
  {
    "text": "Infinite Scroll",
    "link": "/21-frontend-system-design/infinite-scroll/"
  },
  {
    "text": "Pagination",
    "link": "/21-frontend-system-design/pagination/"
  },
  {
    "text": "Feature Flags",
    "link": "/21-frontend-system-design/feature-flags/"
  },
  {
    "text": "Realtime Applications",
    "link": "/21-frontend-system-design/realtime-applications/"
  },
  {
    "text": "Search UI",
    "link": "/21-frontend-system-design/search-ui/"
  },
  {
    "text": "Upload Pipelines",
    "link": "/21-frontend-system-design/upload-pipelines/"
  },
  {
    "text": "Multi-Tenant UI",
    "link": "/21-frontend-system-design/multi-tenant-ui/"
  },
  {
    "text": "Internationalized Apps",
    "link": "/21-frontend-system-design/internationalized-apps/"
  },
  {
    "text": "Designing Design Systems",
    "link": "/21-frontend-system-design/designing-design-systems/"
  }
]
