import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/22-design-patterns/"
  },
  {
    "text": "MVC, MVP, MVVM",
    "link": "/22-design-patterns/mvc-mvp-mvvm/"
  },
  {
    "text": "Container / Presentational",
    "link": "/22-design-patterns/container-presentational/"
  },
  {
    "text": "Hooks Patterns",
    "link": "/22-design-patterns/hooks-patterns/"
  },
  {
    "text": "Compound Components",
    "link": "/22-design-patterns/compound-components/"
  },
  {
    "text": "Render Props",
    "link": "/22-design-patterns/render-props/"
  },
  {
    "text": "Higher-Order Components",
    "link": "/22-design-patterns/hoc/"
  },
  {
    "text": "Provider Pattern",
    "link": "/22-design-patterns/provider-pattern/"
  },
  {
    "text": "Observer Pattern",
    "link": "/22-design-patterns/observer-pattern/"
  },
  {
    "text": "Module Pattern",
    "link": "/22-design-patterns/module-pattern/"
  },
  {
    "text": "Factory and Builder",
    "link": "/22-design-patterns/factory-and-builder/"
  },
  {
    "text": "When Patterns Hurt",
    "link": "/22-design-patterns/when-patterns-hurt/"
  }
]
