import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/23-pwa-and-offline/"
  },
  {
    "text": "PWA Overview",
    "link": "/23-pwa-and-offline/pwa-overview/"
  },
  {
    "text": "Service Worker Lifecycle",
    "link": "/23-pwa-and-offline/service-worker-lifecycle/"
  },
  {
    "text": "Service Worker Caching Strategies",
    "link": "/23-pwa-and-offline/caching-strategies-sw/"
  },
  {
    "text": "Background Sync",
    "link": "/23-pwa-and-offline/background-sync/"
  },
  {
    "text": "Web App Manifest",
    "link": "/23-pwa-and-offline/web-app-manifest/"
  },
  {
    "text": "Installability",
    "link": "/23-pwa-and-offline/installability/"
  },
  {
    "text": "Push Notifications",
    "link": "/23-pwa-and-offline/push-notifications/"
  },
  {
    "text": "Offline UX",
    "link": "/23-pwa-and-offline/offline-ux/"
  }
]
