import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/24-interview-preparation/"
  },
  {
    "text": "How to Answer",
    "link": "/24-interview-preparation/how-to-answer/"
  },
  {
    "text": "JavaScript Interview Questions",
    "link": "/24-interview-preparation/javascript-interview-questions/"
  },
  {
    "text": "Browser Interview Questions",
    "link": "/24-interview-preparation/browser-interview-questions/"
  },
  {
    "text": "React Interview Questions",
    "link": "/24-interview-preparation/react-interview-questions/"
  },
  {
    "text": "Next.js Interview Questions",
    "link": "/24-interview-preparation/nextjs-interview-questions/"
  },
  {
    "text": "Network Interview Questions",
    "link": "/24-interview-preparation/network-interview-questions/"
  },
  {
    "text": "CSS Interview Questions",
    "link": "/24-interview-preparation/css-interview-questions/"
  },
  {
    "text": "TypeScript Interview Questions",
    "link": "/24-interview-preparation/typescript-interview-questions/"
  },
  {
    "text": "Performance Interview Questions",
    "link": "/24-interview-preparation/performance-interview-questions/"
  },
  {
    "text": "Security Interview Questions",
    "link": "/24-interview-preparation/security-interview-questions/"
  },
  {
    "text": "System Design Interview Questions",
    "link": "/24-interview-preparation/system-design-interview-questions/"
  }
]
