import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "Module overview",
    "link": "/25-appendix/"
  },
  {
    "text": "Browser Compatibility",
    "link": "/25-appendix/browser-compatibility/"
  },
  {
    "text": "HTTP Status Codes",
    "link": "/25-appendix/http-status-codes/"
  },
  {
    "text": "MIME Types",
    "link": "/25-appendix/mime-types/"
  },
  {
    "text": "Priority Hints Cheatsheet",
    "link": "/25-appendix/priority-hints-cheatsheet/"
  },
  {
    "text": "Glossary Export",
    "link": "/25-appendix/glossary-export/"
  },
  {
    "text": "Curriculum Changelog",
    "link": "/25-appendix/curriculum-changelog/"
  },
  {
    "text": "Further Reading Policy",
    "link": "/25-appendix/further-reading-policy/"
  }
]
