import type { DefaultTheme } from 'vitepress'
import { sidebar as sidebar_00_foundations } from './00-foundations.js'
import { sidebar as sidebar_01_computer_science } from './01-computer-science.js'
import { sidebar as sidebar_02_internet } from './02-internet.js'
import { sidebar as sidebar_03_browser } from './03-browser.js'
import { sidebar as sidebar_04_html } from './04-html.js'
import { sidebar as sidebar_05_css } from './05-css.js'
import { sidebar as sidebar_06_javascript } from './06-javascript.js'
import { sidebar as sidebar_07_typescript } from './07-typescript.js'
import { sidebar as sidebar_08_jsx_and_react_runtime } from './08-jsx-and-react-runtime.js'
import { sidebar as sidebar_09_browser_apis } from './09-browser-apis.js'
import { sidebar as sidebar_10_react } from './10-react.js'
import { sidebar as sidebar_11_nextjs } from './11-nextjs.js'
import { sidebar as sidebar_12_rendering } from './12-rendering.js'
import { sidebar as sidebar_13_performance } from './13-performance.js'
import { sidebar as sidebar_14_build_tools } from './14-build-tools.js'
import { sidebar as sidebar_15_architecture } from './15-architecture.js'
import { sidebar as sidebar_16_testing } from './16-testing.js'
import { sidebar as sidebar_17_security } from './17-security.js'
import { sidebar as sidebar_18_accessibility } from './18-accessibility.js'
import { sidebar as sidebar_19_deployment } from './19-deployment.js'
import { sidebar as sidebar_20_observability } from './20-observability.js'
import { sidebar as sidebar_21_frontend_system_design } from './21-frontend-system-design.js'
import { sidebar as sidebar_22_design_patterns } from './22-design-patterns.js'
import { sidebar as sidebar_23_pwa_and_offline } from './23-pwa-and-offline.js'
import { sidebar as sidebar_24_interview_preparation } from './24-interview-preparation.js'
import { sidebar as sidebar_25_appendix } from './25-appendix.js'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebars: DefaultTheme.Sidebar = {
  '/00-foundations/': sidebar_00_foundations,
  '/01-computer-science/': sidebar_01_computer_science,
  '/02-internet/': sidebar_02_internet,
  '/03-browser/': sidebar_03_browser,
  '/04-html/': sidebar_04_html,
  '/05-css/': sidebar_05_css,
  '/06-javascript/': sidebar_06_javascript,
  '/07-typescript/': sidebar_07_typescript,
  '/08-jsx-and-react-runtime/': sidebar_08_jsx_and_react_runtime,
  '/09-browser-apis/': sidebar_09_browser_apis,
  '/10-react/': sidebar_10_react,
  '/11-nextjs/': sidebar_11_nextjs,
  '/12-rendering/': sidebar_12_rendering,
  '/13-performance/': sidebar_13_performance,
  '/14-build-tools/': sidebar_14_build_tools,
  '/15-architecture/': sidebar_15_architecture,
  '/16-testing/': sidebar_16_testing,
  '/17-security/': sidebar_17_security,
  '/18-accessibility/': sidebar_18_accessibility,
  '/19-deployment/': sidebar_19_deployment,
  '/20-observability/': sidebar_20_observability,
  '/21-frontend-system-design/': sidebar_21_frontend_system_design,
  '/22-design-patterns/': sidebar_22_design_patterns,
  '/23-pwa-and-offline/': sidebar_23_pwa_and_offline,
  '/24-interview-preparation/': sidebar_24_interview_preparation,
  '/25-appendix/': sidebar_25_appendix,
}
