// AUTO-GENERATED by scripts/generate-topic-map.ts — do not edit by hand
export const topicMap: Record<string, { href: string; title: string }> = {
  "00-foundations.start-here": {
    "href": "/00-foundations/start-here/",
    "title": "Start Here"
  },
  "00-foundations.how-the-web-works-map": {
    "href": "/00-foundations/how-the-web-works-map/",
    "title": "How the Web Works Map"
  },
  "00-foundations.how-to-read-this-handbook": {
    "href": "/00-foundations/how-to-read-this-handbook/",
    "title": "How to Read This Handbook"
  },
  "00-foundations.prerequisites-checklist": {
    "href": "/00-foundations/prerequisites-checklist/",
    "title": "Prerequisites Checklist"
  },
  "00-foundations.conventions-used": {
    "href": "/00-foundations/conventions-used/",
    "title": "Conventions Used"
  },
  "01-computer-science.binary": {
    "href": "/01-computer-science/binary/",
    "title": "Binary"
  },
  "01-computer-science.bits-and-bytes": {
    "href": "/01-computer-science/bits-and-bytes/",
    "title": "Bits and Bytes"
  },
  "01-computer-science.cpu": {
    "href": "/01-computer-science/cpu/",
    "title": "CPU"
  },
  "01-computer-science.memory": {
    "href": "/01-computer-science/memory/",
    "title": "Memory"
  },
  "01-computer-science.stack": {
    "href": "/01-computer-science/stack/",
    "title": "Stack"
  },
  "01-computer-science.heap": {
    "href": "/01-computer-science/heap/",
    "title": "Heap"
  },
  "01-computer-science.process": {
    "href": "/01-computer-science/process/",
    "title": "Process"
  },
  "01-computer-science.thread": {
    "href": "/01-computer-science/thread/",
    "title": "Thread"
  },
  "01-computer-science.event-loop-cs": {
    "href": "/01-computer-science/event-loop-cs/",
    "title": "Event Loop (Runtime View)"
  },
  "01-computer-science.compiler": {
    "href": "/01-computer-science/compiler/",
    "title": "Compiler"
  },
  "01-computer-science.interpreter": {
    "href": "/01-computer-science/interpreter/",
    "title": "Interpreter"
  },
  "01-computer-science.runtime": {
    "href": "/01-computer-science/runtime/",
    "title": "Runtime"
  },
  "01-computer-science.garbage-collection": {
    "href": "/01-computer-science/garbage-collection/",
    "title": "Garbage Collection"
  },
  "01-computer-science.time-complexity": {
    "href": "/01-computer-science/time-complexity/",
    "title": "Time Complexity"
  },
  "01-computer-science.space-complexity": {
    "href": "/01-computer-science/space-complexity/",
    "title": "Space Complexity"
  },
  "01-computer-science.big-o": {
    "href": "/01-computer-science/big-o/",
    "title": "Big O"
  },
  "01-computer-science.data-structures": {
    "href": "/01-computer-science/data-structures/",
    "title": "Data Structures"
  },
  "01-computer-science.data-structures-array": {
    "href": "/01-computer-science/data-structures/array/",
    "title": "Array"
  },
  "01-computer-science.data-structures-linked-list": {
    "href": "/01-computer-science/data-structures/linked-list/",
    "title": "Linked List"
  },
  "01-computer-science.data-structures-stack-ds": {
    "href": "/01-computer-science/data-structures/stack-ds/",
    "title": "Stack (Data Structure)"
  },
  "01-computer-science.data-structures-queue": {
    "href": "/01-computer-science/data-structures/queue/",
    "title": "Queue"
  },
  "01-computer-science.data-structures-hash-table": {
    "href": "/01-computer-science/data-structures/hash-table/",
    "title": "Hash Table"
  },
  "01-computer-science.data-structures-tree": {
    "href": "/01-computer-science/data-structures/tree/",
    "title": "Tree"
  },
  "01-computer-science.data-structures-graph": {
    "href": "/01-computer-science/data-structures/graph/",
    "title": "Graph"
  },
  "01-computer-science.algorithms": {
    "href": "/01-computer-science/algorithms/",
    "title": "Algorithms"
  },
  "01-computer-science.algorithms-searching": {
    "href": "/01-computer-science/algorithms/searching/",
    "title": "Searching"
  },
  "01-computer-science.algorithms-sorting": {
    "href": "/01-computer-science/algorithms/sorting/",
    "title": "Sorting"
  },
  "01-computer-science.algorithms-recursion": {
    "href": "/01-computer-science/algorithms/recursion/",
    "title": "Recursion"
  },
  "01-computer-science.algorithms-dynamic-programming-intro": {
    "href": "/01-computer-science/algorithms/dynamic-programming-intro/",
    "title": "Dynamic Programming Intro"
  },
  "02-internet.what-is-the-internet": {
    "href": "/02-internet/what-is-the-internet/",
    "title": "What is the Internet"
  },
  "02-internet.client": {
    "href": "/02-internet/client/",
    "title": "Client"
  },
  "02-internet.server": {
    "href": "/02-internet/server/",
    "title": "Server"
  },
  "02-internet.isp": {
    "href": "/02-internet/isp/",
    "title": "ISP"
  },
  "02-internet.router": {
    "href": "/02-internet/router/",
    "title": "Router"
  },
  "02-internet.switch": {
    "href": "/02-internet/switch/",
    "title": "Switch"
  },
  "02-internet.dns": {
    "href": "/02-internet/dns/",
    "title": "DNS"
  },
  "02-internet.domain": {
    "href": "/02-internet/domain/",
    "title": "Domain"
  },
  "02-internet.ip": {
    "href": "/02-internet/ip/",
    "title": "IP"
  },
  "02-internet.ipv4": {
    "href": "/02-internet/ipv4/",
    "title": "IPv4"
  },
  "02-internet.ipv6": {
    "href": "/02-internet/ipv6/",
    "title": "IPv6"
  },
  "02-internet.tcp": {
    "href": "/02-internet/tcp/",
    "title": "TCP"
  },
  "02-internet.udp": {
    "href": "/02-internet/udp/",
    "title": "UDP"
  },
  "02-internet.http": {
    "href": "/02-internet/http/",
    "title": "HTTP"
  },
  "02-internet.https": {
    "href": "/02-internet/https/",
    "title": "HTTPS"
  },
  "02-internet.ssl": {
    "href": "/02-internet/ssl/",
    "title": "SSL"
  },
  "02-internet.tls": {
    "href": "/02-internet/tls/",
    "title": "TLS"
  },
  "02-internet.ssh": {
    "href": "/02-internet/ssh/",
    "title": "SSH"
  },
  "02-internet.websocket": {
    "href": "/02-internet/websocket/",
    "title": "WebSocket"
  },
  "02-internet.sse": {
    "href": "/02-internet/sse/",
    "title": "Server-Sent Events"
  },
  "02-internet.http2": {
    "href": "/02-internet/http2/",
    "title": "HTTP/2"
  },
  "02-internet.http3": {
    "href": "/02-internet/http3/",
    "title": "HTTP/3"
  },
  "02-internet.quic": {
    "href": "/02-internet/quic/",
    "title": "QUIC"
  },
  "02-internet.cookies": {
    "href": "/02-internet/cookies/",
    "title": "Cookies"
  },
  "02-internet.sessions": {
    "href": "/02-internet/sessions/",
    "title": "Sessions"
  },
  "02-internet.authentication": {
    "href": "/02-internet/authentication/",
    "title": "Authentication"
  },
  "02-internet.authorization": {
    "href": "/02-internet/authorization/",
    "title": "Authorization"
  },
  "02-internet.rest": {
    "href": "/02-internet/rest/",
    "title": "REST"
  },
  "02-internet.graphql": {
    "href": "/02-internet/graphql/",
    "title": "GraphQL"
  },
  "02-internet.http-caching": {
    "href": "/02-internet/http-caching/",
    "title": "HTTP Caching"
  },
  "02-internet.cdn-basics": {
    "href": "/02-internet/cdn-basics/",
    "title": "CDN Basics"
  },
  "02-internet.load-balancing-basics": {
    "href": "/02-internet/load-balancing-basics/",
    "title": "Load Balancing Basics"
  },
  "03-browser.browser-architecture": {
    "href": "/03-browser/browser-architecture/",
    "title": "Browser Architecture"
  },
  "03-browser.multi-process-model": {
    "href": "/03-browser/multi-process-model/",
    "title": "Multi-Process Model"
  },
  "03-browser.rendering-engine": {
    "href": "/03-browser/rendering-engine/",
    "title": "Rendering Engine"
  },
  "03-browser.javascript-engine": {
    "href": "/03-browser/javascript-engine/",
    "title": "JavaScript Engine"
  },
  "03-browser.v8": {
    "href": "/03-browser/v8/",
    "title": "V8"
  },
  "03-browser.spidermonkey": {
    "href": "/03-browser/spidermonkey/",
    "title": "SpiderMonkey"
  },
  "03-browser.javascriptcore": {
    "href": "/03-browser/javascriptcore/",
    "title": "JavaScriptCore"
  },
  "03-browser.parsing-html": {
    "href": "/03-browser/parsing-html/",
    "title": "Parsing HTML"
  },
  "03-browser.parsing-css": {
    "href": "/03-browser/parsing-css/",
    "title": "Parsing CSS"
  },
  "03-browser.dom": {
    "href": "/03-browser/dom/",
    "title": "DOM"
  },
  "03-browser.cssom": {
    "href": "/03-browser/cssom/",
    "title": "CSSOM"
  },
  "03-browser.render-tree": {
    "href": "/03-browser/render-tree/",
    "title": "Render Tree"
  },
  "03-browser.layout": {
    "href": "/03-browser/layout/",
    "title": "Layout"
  },
  "03-browser.paint": {
    "href": "/03-browser/paint/",
    "title": "Paint"
  },
  "03-browser.composite": {
    "href": "/03-browser/composite/",
    "title": "Composite"
  },
  "03-browser.gpu": {
    "href": "/03-browser/gpu/",
    "title": "GPU"
  },
  "03-browser.reflow": {
    "href": "/03-browser/reflow/",
    "title": "Reflow"
  },
  "03-browser.repaint": {
    "href": "/03-browser/repaint/",
    "title": "Repaint"
  },
  "03-browser.critical-rendering-path": {
    "href": "/03-browser/critical-rendering-path/",
    "title": "Critical Rendering Path"
  },
  "03-browser.call-stack": {
    "href": "/03-browser/call-stack/",
    "title": "Call Stack"
  },
  "03-browser.task-queue": {
    "href": "/03-browser/task-queue/",
    "title": "Task Queue"
  },
  "03-browser.event-loop": {
    "href": "/03-browser/event-loop/",
    "title": "Event Loop"
  },
  "03-browser.microtasks": {
    "href": "/03-browser/microtasks/",
    "title": "Microtasks"
  },
  "03-browser.macrotasks": {
    "href": "/03-browser/macrotasks/",
    "title": "Macrotasks"
  },
  "03-browser.memory-management": {
    "href": "/03-browser/memory-management/",
    "title": "Memory Management"
  },
  "03-browser.garbage-collection-browser": {
    "href": "/03-browser/garbage-collection-browser/",
    "title": "Garbage Collection in the Browser"
  },
  "03-browser.devtools-rendering-panel": {
    "href": "/03-browser/devtools-rendering-panel/",
    "title": "DevTools Rendering Panel"
  },
  "04-html.semantic-html": {
    "href": "/04-html/semantic-html/",
    "title": "Semantic HTML"
  },
  "04-html.document-structure": {
    "href": "/04-html/document-structure/",
    "title": "Document Structure"
  },
  "04-html.forms": {
    "href": "/04-html/forms/",
    "title": "Forms"
  },
  "04-html.media-elements": {
    "href": "/04-html/media-elements/",
    "title": "Media Elements"
  },
  "04-html.metadata": {
    "href": "/04-html/metadata/",
    "title": "Metadata"
  },
  "04-html.seo-basics": {
    "href": "/04-html/seo-basics/",
    "title": "SEO Basics"
  },
  "04-html.scripts": {
    "href": "/04-html/scripts/",
    "title": "Scripts"
  },
  "04-html.defer": {
    "href": "/04-html/defer/",
    "title": "defer"
  },
  "04-html.async": {
    "href": "/04-html/async/",
    "title": "async"
  },
  "04-html.module-scripts": {
    "href": "/04-html/module-scripts/",
    "title": "Module Scripts"
  },
  "04-html.preload": {
    "href": "/04-html/preload/",
    "title": "preload"
  },
  "04-html.prefetch": {
    "href": "/04-html/prefetch/",
    "title": "prefetch"
  },
  "04-html.preconnect": {
    "href": "/04-html/preconnect/",
    "title": "preconnect"
  },
  "04-html.modulepreload": {
    "href": "/04-html/modulepreload/",
    "title": "modulepreload"
  },
  "04-html.templates-and-slots": {
    "href": "/04-html/templates-and-slots/",
    "title": "Templates and Slots"
  },
  "05-css.cascade": {
    "href": "/05-css/cascade/",
    "title": "Cascade"
  },
  "05-css.specificity": {
    "href": "/05-css/specificity/",
    "title": "Specificity"
  },
  "05-css.inheritance": {
    "href": "/05-css/inheritance/",
    "title": "Inheritance"
  },
  "05-css.box-model": {
    "href": "/05-css/box-model/",
    "title": "Box Model"
  },
  "05-css.positioning": {
    "href": "/05-css/positioning/",
    "title": "Positioning"
  },
  "05-css.flexbox": {
    "href": "/05-css/flexbox/",
    "title": "Flexbox"
  },
  "05-css.grid": {
    "href": "/05-css/grid/",
    "title": "Grid"
  },
  "05-css.responsive-design": {
    "href": "/05-css/responsive-design/",
    "title": "Responsive Design"
  },
  "05-css.media-queries": {
    "href": "/05-css/media-queries/",
    "title": "Media Queries"
  },
  "05-css.container-queries": {
    "href": "/05-css/container-queries/",
    "title": "Container Queries"
  },
  "05-css.animations": {
    "href": "/05-css/animations/",
    "title": "Animations"
  },
  "05-css.transitions": {
    "href": "/05-css/transitions/",
    "title": "Transitions"
  },
  "05-css.transforms": {
    "href": "/05-css/transforms/",
    "title": "Transforms"
  },
  "05-css.compositing": {
    "href": "/05-css/compositing/",
    "title": "Compositing"
  },
  "05-css.containment": {
    "href": "/05-css/containment/",
    "title": "Containment"
  },
  "05-css.layers": {
    "href": "/05-css/layers/",
    "title": "Layers"
  },
  "05-css.modern-css": {
    "href": "/05-css/modern-css/",
    "title": "Modern CSS"
  },
  "05-css.css-architecture": {
    "href": "/05-css/css-architecture/",
    "title": "CSS Architecture"
  },
  "06-javascript.variables": {
    "href": "/06-javascript/variables/",
    "title": "Variables"
  },
  "06-javascript.types-and-values": {
    "href": "/06-javascript/types-and-values/",
    "title": "Types and Values"
  },
  "06-javascript.scope": {
    "href": "/06-javascript/scope/",
    "title": "Scope"
  },
  "06-javascript.closures": {
    "href": "/06-javascript/closures/",
    "title": "Closures"
  },
  "06-javascript.hoisting": {
    "href": "/06-javascript/hoisting/",
    "title": "Hoisting"
  },
  "06-javascript.execution-context": {
    "href": "/06-javascript/execution-context/",
    "title": "Execution Context"
  },
  "06-javascript.lexical-environment": {
    "href": "/06-javascript/lexical-environment/",
    "title": "Lexical Environment"
  },
  "06-javascript.prototype": {
    "href": "/06-javascript/prototype/",
    "title": "Prototype"
  },
  "06-javascript.prototype-chain": {
    "href": "/06-javascript/prototype-chain/",
    "title": "Prototype Chain"
  },
  "06-javascript.this": {
    "href": "/06-javascript/this/",
    "title": "this"
  },
  "06-javascript.classes": {
    "href": "/06-javascript/classes/",
    "title": "Classes"
  },
  "06-javascript.functions": {
    "href": "/06-javascript/functions/",
    "title": "Functions"
  },
  "06-javascript.objects": {
    "href": "/06-javascript/objects/",
    "title": "Objects"
  },
  "06-javascript.arrays": {
    "href": "/06-javascript/arrays/",
    "title": "Arrays"
  },
  "06-javascript.modules": {
    "href": "/06-javascript/modules/",
    "title": "Modules"
  },
  "06-javascript.es-modules": {
    "href": "/06-javascript/es-modules/",
    "title": "ES Modules"
  },
  "06-javascript.commonjs": {
    "href": "/06-javascript/commonjs/",
    "title": "CommonJS"
  },
  "06-javascript.async-programming": {
    "href": "/06-javascript/async-programming/",
    "title": "Async Programming"
  },
  "06-javascript.event-loop-js": {
    "href": "/06-javascript/event-loop-js/",
    "title": "Event Loop (JavaScript View)"
  },
  "06-javascript.promise": {
    "href": "/06-javascript/promise/",
    "title": "Promise"
  },
  "06-javascript.async-await": {
    "href": "/06-javascript/async-await/",
    "title": "Async/Await"
  },
  "06-javascript.generator": {
    "href": "/06-javascript/generator/",
    "title": "Generator"
  },
  "06-javascript.iterator": {
    "href": "/06-javascript/iterator/",
    "title": "Iterator"
  },
  "06-javascript.fetch-api": {
    "href": "/06-javascript/fetch-api/",
    "title": "Fetch API"
  },
  "06-javascript.abortcontroller": {
    "href": "/06-javascript/abortcontroller/",
    "title": "AbortController"
  },
  "06-javascript.proxy": {
    "href": "/06-javascript/proxy/",
    "title": "Proxy"
  },
  "06-javascript.reflect": {
    "href": "/06-javascript/reflect/",
    "title": "Reflect"
  },
  "06-javascript.symbols": {
    "href": "/06-javascript/symbols/",
    "title": "Symbols"
  },
  "06-javascript.weakmap": {
    "href": "/06-javascript/weakmap/",
    "title": "WeakMap"
  },
  "06-javascript.weakset": {
    "href": "/06-javascript/weakset/",
    "title": "WeakSet"
  },
  "06-javascript.error-handling": {
    "href": "/06-javascript/error-handling/",
    "title": "Error Handling"
  },
  "06-javascript.strict-mode": {
    "href": "/06-javascript/strict-mode/",
    "title": "Strict Mode"
  },
  "06-javascript.memory-and-references": {
    "href": "/06-javascript/memory-and-references/",
    "title": "Memory and References"
  },
  "07-typescript.types": {
    "href": "/07-typescript/types/",
    "title": "Types"
  },
  "07-typescript.interfaces": {
    "href": "/07-typescript/interfaces/",
    "title": "Interfaces"
  },
  "07-typescript.type-vs-interface": {
    "href": "/07-typescript/type-vs-interface/",
    "title": "Type vs Interface"
  },
  "07-typescript.generics": {
    "href": "/07-typescript/generics/",
    "title": "Generics"
  },
  "07-typescript.utility-types": {
    "href": "/07-typescript/utility-types/",
    "title": "Utility Types"
  },
  "07-typescript.type-inference": {
    "href": "/07-typescript/type-inference/",
    "title": "Type Inference"
  },
  "07-typescript.advanced-types": {
    "href": "/07-typescript/advanced-types/",
    "title": "Advanced Types"
  },
  "07-typescript.declaration-files": {
    "href": "/07-typescript/declaration-files/",
    "title": "Declaration Files"
  },
  "07-typescript.tsconfig": {
    "href": "/07-typescript/tsconfig/",
    "title": "tsconfig"
  },
  "07-typescript.compiler": {
    "href": "/07-typescript/compiler/",
    "title": "TypeScript Compiler"
  },
  "07-typescript.type-narrowing": {
    "href": "/07-typescript/type-narrowing/",
    "title": "Type Narrowing"
  },
  "07-typescript.satisfies": {
    "href": "/07-typescript/satisfies/",
    "title": "satisfies"
  },
  "07-typescript.enums-and-alternatives": {
    "href": "/07-typescript/enums-and-alternatives/",
    "title": "Enums and Alternatives"
  },
  "07-typescript.typescript-with-react": {
    "href": "/07-typescript/typescript-with-react/",
    "title": "TypeScript with React"
  },
  "08-jsx-and-react-runtime.jsx": {
    "href": "/08-jsx-and-react-runtime/jsx/",
    "title": "JSX"
  },
  "08-jsx-and-react-runtime.babel": {
    "href": "/08-jsx-and-react-runtime/babel/",
    "title": "Babel"
  },
  "08-jsx-and-react-runtime.ast": {
    "href": "/08-jsx-and-react-runtime/ast/",
    "title": "AST"
  },
  "08-jsx-and-react-runtime.jsx-transform": {
    "href": "/08-jsx-and-react-runtime/jsx-transform/",
    "title": "JSX Transform"
  },
  "08-jsx-and-react-runtime.react-createelement": {
    "href": "/08-jsx-and-react-runtime/react-createelement/",
    "title": "React.createElement"
  },
  "08-jsx-and-react-runtime.virtual-dom": {
    "href": "/08-jsx-and-react-runtime/virtual-dom/",
    "title": "Virtual DOM"
  },
  "08-jsx-and-react-runtime.fiber": {
    "href": "/08-jsx-and-react-runtime/fiber/",
    "title": "Fiber"
  },
  "08-jsx-and-react-runtime.reconciliation": {
    "href": "/08-jsx-and-react-runtime/reconciliation/",
    "title": "Reconciliation"
  },
  "08-jsx-and-react-runtime.diffing-algorithm": {
    "href": "/08-jsx-and-react-runtime/diffing-algorithm/",
    "title": "Diffing Algorithm"
  },
  "08-jsx-and-react-runtime.keys": {
    "href": "/08-jsx-and-react-runtime/keys/",
    "title": "Keys"
  },
  "08-jsx-and-react-runtime.fragments": {
    "href": "/08-jsx-and-react-runtime/fragments/",
    "title": "Fragments"
  },
  "09-browser-apis.localstorage": {
    "href": "/09-browser-apis/localstorage/",
    "title": "localStorage"
  },
  "09-browser-apis.sessionstorage": {
    "href": "/09-browser-apis/sessionstorage/",
    "title": "sessionStorage"
  },
  "09-browser-apis.indexeddb": {
    "href": "/09-browser-apis/indexeddb/",
    "title": "IndexedDB"
  },
  "09-browser-apis.cache-storage": {
    "href": "/09-browser-apis/cache-storage/",
    "title": "Cache Storage"
  },
  "09-browser-apis.history-api": {
    "href": "/09-browser-apis/history-api/",
    "title": "History API"
  },
  "09-browser-apis.clipboard-api": {
    "href": "/09-browser-apis/clipboard-api/",
    "title": "Clipboard API"
  },
  "09-browser-apis.intersection-observer": {
    "href": "/09-browser-apis/intersection-observer/",
    "title": "Intersection Observer"
  },
  "09-browser-apis.mutation-observer": {
    "href": "/09-browser-apis/mutation-observer/",
    "title": "Mutation Observer"
  },
  "09-browser-apis.resize-observer": {
    "href": "/09-browser-apis/resize-observer/",
    "title": "Resize Observer"
  },
  "09-browser-apis.broadcast-channel": {
    "href": "/09-browser-apis/broadcast-channel/",
    "title": "Broadcast Channel"
  },
  "09-browser-apis.web-workers": {
    "href": "/09-browser-apis/web-workers/",
    "title": "Web Workers"
  },
  "09-browser-apis.service-workers": {
    "href": "/09-browser-apis/service-workers/",
    "title": "Service Workers"
  },
  "09-browser-apis.notifications": {
    "href": "/09-browser-apis/notifications/",
    "title": "Notifications"
  },
  "09-browser-apis.geolocation": {
    "href": "/09-browser-apis/geolocation/",
    "title": "Geolocation"
  },
  "09-browser-apis.web-sockets-api": {
    "href": "/09-browser-apis/web-sockets-api/",
    "title": "WebSocket API"
  },
  "09-browser-apis.streams-api": {
    "href": "/09-browser-apis/streams-api/",
    "title": "Streams API"
  },
  "09-browser-apis.file-api": {
    "href": "/09-browser-apis/file-api/",
    "title": "File API"
  },
  "09-browser-apis.web-components": {
    "href": "/09-browser-apis/web-components/",
    "title": "Web Components"
  },
  "09-browser-apis.custom-elements": {
    "href": "/09-browser-apis/custom-elements/",
    "title": "Custom Elements"
  },
  "09-browser-apis.shadow-dom": {
    "href": "/09-browser-apis/shadow-dom/",
    "title": "Shadow DOM"
  },
  "10-react.philosophy": {
    "href": "/10-react/philosophy/",
    "title": "React Philosophy"
  },
  "10-react.components": {
    "href": "/10-react/components/",
    "title": "Components"
  },
  "10-react.props": {
    "href": "/10-react/props/",
    "title": "Props"
  },
  "10-react.state": {
    "href": "/10-react/state/",
    "title": "State"
  },
  "10-react.hooks": {
    "href": "/10-react/hooks/",
    "title": "Hooks"
  },
  "10-react.rules-of-hooks": {
    "href": "/10-react/rules-of-hooks/",
    "title": "Rules of Hooks"
  },
  "10-react.context": {
    "href": "/10-react/context/",
    "title": "Context"
  },
  "10-react.reducer": {
    "href": "/10-react/reducer/",
    "title": "Reducer"
  },
  "10-react.memoization": {
    "href": "/10-react/memoization/",
    "title": "Memoization in React"
  },
  "10-react.react-memo": {
    "href": "/10-react/react-memo/",
    "title": "React.memo"
  },
  "10-react.usememo": {
    "href": "/10-react/usememo/",
    "title": "useMemo"
  },
  "10-react.usecallback": {
    "href": "/10-react/usecallback/",
    "title": "useCallback"
  },
  "10-react.useref": {
    "href": "/10-react/useref/",
    "title": "useRef"
  },
  "10-react.useeffect": {
    "href": "/10-react/useeffect/",
    "title": "useEffect"
  },
  "10-react.uselayouteffect": {
    "href": "/10-react/uselayouteffect/",
    "title": "useLayoutEffect"
  },
  "10-react.useimperativehandle": {
    "href": "/10-react/useimperativehandle/",
    "title": "useImperativeHandle"
  },
  "10-react.useid": {
    "href": "/10-react/useid/",
    "title": "useId"
  },
  "10-react.use": {
    "href": "/10-react/use/",
    "title": "use"
  },
  "10-react.suspense": {
    "href": "/10-react/suspense/",
    "title": "Suspense"
  },
  "10-react.lazy-loading": {
    "href": "/10-react/lazy-loading/",
    "title": "Lazy Loading"
  },
  "10-react.error-boundaries": {
    "href": "/10-react/error-boundaries/",
    "title": "Error Boundaries"
  },
  "10-react.portals": {
    "href": "/10-react/portals/",
    "title": "Portals"
  },
  "10-react.concurrent-rendering": {
    "href": "/10-react/concurrent-rendering/",
    "title": "Concurrent Rendering"
  },
  "10-react.transitions": {
    "href": "/10-react/transitions/",
    "title": "Transitions"
  },
  "10-react.deferred-value": {
    "href": "/10-react/deferred-value/",
    "title": "useDeferredValue"
  },
  "10-react.strict-mode": {
    "href": "/10-react/strict-mode/",
    "title": "Strict Mode"
  },
  "10-react.react-compiler": {
    "href": "/10-react/react-compiler/",
    "title": "React Compiler"
  },
  "10-react.server-components-overview": {
    "href": "/10-react/server-components-overview/",
    "title": "Server Components Overview"
  },
  "10-react.effects-vs-events": {
    "href": "/10-react/effects-vs-events/",
    "title": "Effects vs Events"
  },
  "11-nextjs.app-router": {
    "href": "/11-nextjs/app-router/",
    "title": "App Router"
  },
  "11-nextjs.pages-router": {
    "href": "/11-nextjs/pages-router/",
    "title": "Pages Router"
  },
  "11-nextjs.routing": {
    "href": "/11-nextjs/routing/",
    "title": "Routing"
  },
  "11-nextjs.layouts": {
    "href": "/11-nextjs/layouts/",
    "title": "Layouts"
  },
  "11-nextjs.nested-layouts": {
    "href": "/11-nextjs/nested-layouts/",
    "title": "Nested Layouts"
  },
  "11-nextjs.templates": {
    "href": "/11-nextjs/templates/",
    "title": "Templates"
  },
  "11-nextjs.loading-ui": {
    "href": "/11-nextjs/loading-ui/",
    "title": "Loading UI"
  },
  "11-nextjs.error-ui": {
    "href": "/11-nextjs/error-ui/",
    "title": "Error UI"
  },
  "11-nextjs.metadata": {
    "href": "/11-nextjs/metadata/",
    "title": "Metadata"
  },
  "11-nextjs.route-handlers": {
    "href": "/11-nextjs/route-handlers/",
    "title": "Route Handlers"
  },
  "11-nextjs.middleware": {
    "href": "/11-nextjs/middleware/",
    "title": "Middleware"
  },
  "11-nextjs.edge-runtime": {
    "href": "/11-nextjs/edge-runtime/",
    "title": "Edge Runtime"
  },
  "11-nextjs.node-runtime": {
    "href": "/11-nextjs/node-runtime/",
    "title": "Node Runtime"
  },
  "11-nextjs.image-optimization": {
    "href": "/11-nextjs/image-optimization/",
    "title": "Image Optimization"
  },
  "11-nextjs.fonts": {
    "href": "/11-nextjs/fonts/",
    "title": "Fonts"
  },
  "11-nextjs.server-components": {
    "href": "/11-nextjs/server-components/",
    "title": "Server Components"
  },
  "11-nextjs.client-components": {
    "href": "/11-nextjs/client-components/",
    "title": "Client Components"
  },
  "11-nextjs.server-actions": {
    "href": "/11-nextjs/server-actions/",
    "title": "Server Actions"
  },
  "11-nextjs.streaming": {
    "href": "/11-nextjs/streaming/",
    "title": "Streaming"
  },
  "11-nextjs.caching": {
    "href": "/11-nextjs/caching/",
    "title": "Caching"
  },
  "11-nextjs.partial-prerendering": {
    "href": "/11-nextjs/partial-prerendering/",
    "title": "Partial Prerendering"
  },
  "11-nextjs.data-fetching": {
    "href": "/11-nextjs/data-fetching/",
    "title": "Data Fetching"
  },
  "11-nextjs.route-groups": {
    "href": "/11-nextjs/route-groups/",
    "title": "Route Groups"
  },
  "11-nextjs.intercepting-routes": {
    "href": "/11-nextjs/intercepting-routes/",
    "title": "Intercepting Routes"
  },
  "11-nextjs.parallel-routes": {
    "href": "/11-nextjs/parallel-routes/",
    "title": "Parallel Routes"
  },
  "12-rendering.csr": {
    "href": "/12-rendering/csr/",
    "title": "Client-Side Rendering"
  },
  "12-rendering.ssr": {
    "href": "/12-rendering/ssr/",
    "title": "Server-Side Rendering"
  },
  "12-rendering.ssg": {
    "href": "/12-rendering/ssg/",
    "title": "Static Site Generation"
  },
  "12-rendering.isr": {
    "href": "/12-rendering/isr/",
    "title": "Incremental Static Regeneration"
  },
  "12-rendering.ppr": {
    "href": "/12-rendering/ppr/",
    "title": "Partial Prerendering"
  },
  "12-rendering.streaming": {
    "href": "/12-rendering/streaming/",
    "title": "Streaming"
  },
  "12-rendering.hydration": {
    "href": "/12-rendering/hydration/",
    "title": "Hydration"
  },
  "12-rendering.progressive-hydration": {
    "href": "/12-rendering/progressive-hydration/",
    "title": "Progressive Hydration"
  },
  "12-rendering.resumability": {
    "href": "/12-rendering/resumability/",
    "title": "Resumability"
  },
  "12-rendering.edge-rendering": {
    "href": "/12-rendering/edge-rendering/",
    "title": "Edge Rendering"
  },
  "12-rendering.cdn": {
    "href": "/12-rendering/cdn/",
    "title": "CDN"
  },
  "12-rendering.browser-cache": {
    "href": "/12-rendering/browser-cache/",
    "title": "Browser Cache"
  },
  "12-rendering.cache-control": {
    "href": "/12-rendering/cache-control/",
    "title": "Cache-Control"
  },
  "12-rendering.etag": {
    "href": "/12-rendering/etag/",
    "title": "ETag"
  },
  "12-rendering.stale-while-revalidate": {
    "href": "/12-rendering/stale-while-revalidate/",
    "title": "Stale While Revalidate"
  },
  "12-rendering.rendering-strategy-decision-tree": {
    "href": "/12-rendering/rendering-strategy-decision-tree/",
    "title": "Rendering Strategy Decision Tree"
  },
  "13-performance.bundle": {
    "href": "/13-performance/bundle/",
    "title": "Bundle"
  },
  "13-performance.chunk": {
    "href": "/13-performance/chunk/",
    "title": "Chunk"
  },
  "13-performance.bundling": {
    "href": "/13-performance/bundling/",
    "title": "Bundling"
  },
  "13-performance.code-splitting": {
    "href": "/13-performance/code-splitting/",
    "title": "Code Splitting"
  },
  "13-performance.tree-shaking": {
    "href": "/13-performance/tree-shaking/",
    "title": "Tree Shaking"
  },
  "13-performance.dead-code-elimination": {
    "href": "/13-performance/dead-code-elimination/",
    "title": "Dead Code Elimination"
  },
  "13-performance.dynamic-import": {
    "href": "/13-performance/dynamic-import/",
    "title": "Dynamic Import"
  },
  "13-performance.lazy-loading": {
    "href": "/13-performance/lazy-loading/",
    "title": "Lazy Loading"
  },
  "13-performance.debounce": {
    "href": "/13-performance/debounce/",
    "title": "Debounce"
  },
  "13-performance.throttle": {
    "href": "/13-performance/throttle/",
    "title": "Throttle"
  },
  "13-performance.memoization-perf": {
    "href": "/13-performance/memoization-perf/",
    "title": "Memoization"
  },
  "13-performance.virtualization": {
    "href": "/13-performance/virtualization/",
    "title": "Virtualization"
  },
  "13-performance.image-optimization-perf": {
    "href": "/13-performance/image-optimization-perf/",
    "title": "Image Optimization"
  },
  "13-performance.font-performance": {
    "href": "/13-performance/font-performance/",
    "title": "Font Performance"
  },
  "13-performance.lighthouse": {
    "href": "/13-performance/lighthouse/",
    "title": "Lighthouse"
  },
  "13-performance.core-web-vitals": {
    "href": "/13-performance/core-web-vitals/",
    "title": "Core Web Vitals"
  },
  "13-performance.lcp": {
    "href": "/13-performance/lcp/",
    "title": "LCP"
  },
  "13-performance.cls": {
    "href": "/13-performance/cls/",
    "title": "CLS"
  },
  "13-performance.inp": {
    "href": "/13-performance/inp/",
    "title": "INP"
  },
  "13-performance.ttfb": {
    "href": "/13-performance/ttfb/",
    "title": "TTFB"
  },
  "13-performance.tti": {
    "href": "/13-performance/tti/",
    "title": "TTI"
  },
  "13-performance.fcp": {
    "href": "/13-performance/fcp/",
    "title": "FCP"
  },
  "13-performance.tbt": {
    "href": "/13-performance/tbt/",
    "title": "TBT"
  },
  "13-performance.profiling": {
    "href": "/13-performance/profiling/",
    "title": "Profiling"
  },
  "13-performance.long-tasks": {
    "href": "/13-performance/long-tasks/",
    "title": "Long Tasks"
  },
  "13-performance.scheduler-yielding": {
    "href": "/13-performance/scheduler-yielding/",
    "title": "Scheduler and Yielding"
  },
  "14-build-tools.nodejs": {
    "href": "/14-build-tools/nodejs/",
    "title": "Node.js"
  },
  "14-build-tools.npm": {
    "href": "/14-build-tools/npm/",
    "title": "npm"
  },
  "14-build-tools.pnpm": {
    "href": "/14-build-tools/pnpm/",
    "title": "pnpm"
  },
  "14-build-tools.yarn": {
    "href": "/14-build-tools/yarn/",
    "title": "Yarn"
  },
  "14-build-tools.bun": {
    "href": "/14-build-tools/bun/",
    "title": "Bun"
  },
  "14-build-tools.module-resolution": {
    "href": "/14-build-tools/module-resolution/",
    "title": "Module Resolution"
  },
  "14-build-tools.webpack": {
    "href": "/14-build-tools/webpack/",
    "title": "Webpack"
  },
  "14-build-tools.rollup": {
    "href": "/14-build-tools/rollup/",
    "title": "Rollup"
  },
  "14-build-tools.vite": {
    "href": "/14-build-tools/vite/",
    "title": "Vite"
  },
  "14-build-tools.turbopack": {
    "href": "/14-build-tools/turbopack/",
    "title": "Turbopack"
  },
  "14-build-tools.rspack": {
    "href": "/14-build-tools/rspack/",
    "title": "Rspack"
  },
  "14-build-tools.parcel": {
    "href": "/14-build-tools/parcel/",
    "title": "Parcel"
  },
  "14-build-tools.babel": {
    "href": "/14-build-tools/babel/",
    "title": "Babel"
  },
  "14-build-tools.swc": {
    "href": "/14-build-tools/swc/",
    "title": "SWC"
  },
  "14-build-tools.esbuild": {
    "href": "/14-build-tools/esbuild/",
    "title": "esbuild"
  },
  "14-build-tools.postcss": {
    "href": "/14-build-tools/postcss/",
    "title": "PostCSS"
  },
  "14-build-tools.source-maps": {
    "href": "/14-build-tools/source-maps/",
    "title": "Source Maps"
  },
  "14-build-tools.monorepo-tooling": {
    "href": "/14-build-tools/monorepo-tooling/",
    "title": "Monorepo Tooling"
  },
  "15-architecture.feature-based-architecture": {
    "href": "/15-architecture/feature-based-architecture/",
    "title": "Feature-Based Architecture"
  },
  "15-architecture.atomic-design": {
    "href": "/15-architecture/atomic-design/",
    "title": "Atomic Design"
  },
  "15-architecture.design-systems": {
    "href": "/15-architecture/design-systems/",
    "title": "Design Systems"
  },
  "15-architecture.monorepo": {
    "href": "/15-architecture/monorepo/",
    "title": "Monorepo"
  },
  "15-architecture.micro-frontends": {
    "href": "/15-architecture/micro-frontends/",
    "title": "Micro Frontends"
  },
  "15-architecture.module-federation": {
    "href": "/15-architecture/module-federation/",
    "title": "Module Federation"
  },
  "15-architecture.state-management": {
    "href": "/15-architecture/state-management/",
    "title": "State Management"
  },
  "15-architecture.redux": {
    "href": "/15-architecture/redux/",
    "title": "Redux"
  },
  "15-architecture.zustand": {
    "href": "/15-architecture/zustand/",
    "title": "Zustand"
  },
  "15-architecture.jotai": {
    "href": "/15-architecture/jotai/",
    "title": "Jotai"
  },
  "15-architecture.tanstack-query": {
    "href": "/15-architecture/tanstack-query/",
    "title": "TanStack Query"
  },
  "15-architecture.react-router": {
    "href": "/15-architecture/react-router/",
    "title": "React Router"
  },
  "15-architecture.url-as-state": {
    "href": "/15-architecture/url-as-state/",
    "title": "URL as State"
  },
  "15-architecture.component-libraries": {
    "href": "/15-architecture/component-libraries/",
    "title": "Component Libraries"
  },
  "15-architecture.api-layer-design": {
    "href": "/15-architecture/api-layer-design/",
    "title": "API Layer Design"
  },
  "15-architecture.error-handling-architecture": {
    "href": "/15-architecture/error-handling-architecture/",
    "title": "Error Handling Architecture"
  },
  "16-testing.testing-pyramid": {
    "href": "/16-testing/testing-pyramid/",
    "title": "Testing Pyramid"
  },
  "16-testing.unit-testing": {
    "href": "/16-testing/unit-testing/",
    "title": "Unit Testing"
  },
  "16-testing.integration-testing": {
    "href": "/16-testing/integration-testing/",
    "title": "Integration Testing"
  },
  "16-testing.e2e-testing": {
    "href": "/16-testing/e2e-testing/",
    "title": "E2E Testing"
  },
  "16-testing.jest": {
    "href": "/16-testing/jest/",
    "title": "Jest"
  },
  "16-testing.vitest": {
    "href": "/16-testing/vitest/",
    "title": "Vitest"
  },
  "16-testing.react-testing-library": {
    "href": "/16-testing/react-testing-library/",
    "title": "React Testing Library"
  },
  "16-testing.cypress": {
    "href": "/16-testing/cypress/",
    "title": "Cypress"
  },
  "16-testing.playwright": {
    "href": "/16-testing/playwright/",
    "title": "Playwright"
  },
  "16-testing.mocking": {
    "href": "/16-testing/mocking/",
    "title": "Mocking"
  },
  "16-testing.spying": {
    "href": "/16-testing/spying/",
    "title": "Spying"
  },
  "16-testing.msw": {
    "href": "/16-testing/msw/",
    "title": "MSW"
  },
  "16-testing.visual-regression": {
    "href": "/16-testing/visual-regression/",
    "title": "Visual Regression"
  },
  "16-testing.accessibility-testing": {
    "href": "/16-testing/accessibility-testing/",
    "title": "Accessibility Testing"
  },
  "16-testing.test-strategy": {
    "href": "/16-testing/test-strategy/",
    "title": "Test Strategy"
  },
  "17-security.threat-model": {
    "href": "/17-security/threat-model/",
    "title": "Threat Model"
  },
  "17-security.xss": {
    "href": "/17-security/xss/",
    "title": "XSS"
  },
  "17-security.csrf": {
    "href": "/17-security/csrf/",
    "title": "CSRF"
  },
  "17-security.cors": {
    "href": "/17-security/cors/",
    "title": "CORS"
  },
  "17-security.csp": {
    "href": "/17-security/csp/",
    "title": "Content Security Policy"
  },
  "17-security.jwt": {
    "href": "/17-security/jwt/",
    "title": "JWT"
  },
  "17-security.oauth": {
    "href": "/17-security/oauth/",
    "title": "OAuth"
  },
  "17-security.oidc": {
    "href": "/17-security/oidc/",
    "title": "OIDC"
  },
  "17-security.cookies-security": {
    "href": "/17-security/cookies-security/",
    "title": "Cookies Security"
  },
  "17-security.samesite": {
    "href": "/17-security/samesite/",
    "title": "SameSite"
  },
  "17-security.secure-cookies": {
    "href": "/17-security/secure-cookies/",
    "title": "Secure Cookies"
  },
  "17-security.https-security": {
    "href": "/17-security/https-security/",
    "title": "HTTPS Security"
  },
  "17-security.clickjacking": {
    "href": "/17-security/clickjacking/",
    "title": "Clickjacking"
  },
  "17-security.prototype-pollution": {
    "href": "/17-security/prototype-pollution/",
    "title": "Prototype Pollution"
  },
  "17-security.supply-chain-security": {
    "href": "/17-security/supply-chain-security/",
    "title": "Supply Chain Security"
  },
  "17-security.secrets-in-frontend": {
    "href": "/17-security/secrets-in-frontend/",
    "title": "Secrets in the Frontend"
  },
  "18-accessibility.why-accessibility": {
    "href": "/18-accessibility/why-accessibility/",
    "title": "Why Accessibility"
  },
  "18-accessibility.wcag": {
    "href": "/18-accessibility/wcag/",
    "title": "WCAG"
  },
  "18-accessibility.aria": {
    "href": "/18-accessibility/aria/",
    "title": "ARIA"
  },
  "18-accessibility.semantic-html-a11y": {
    "href": "/18-accessibility/semantic-html-a11y/",
    "title": "Semantic HTML for Accessibility"
  },
  "18-accessibility.keyboard-navigation": {
    "href": "/18-accessibility/keyboard-navigation/",
    "title": "Keyboard Navigation"
  },
  "18-accessibility.focus-management": {
    "href": "/18-accessibility/focus-management/",
    "title": "Focus Management"
  },
  "18-accessibility.screen-readers": {
    "href": "/18-accessibility/screen-readers/",
    "title": "Screen Readers"
  },
  "18-accessibility.color-and-contrast": {
    "href": "/18-accessibility/color-and-contrast/",
    "title": "Color and Contrast"
  },
  "18-accessibility.forms-a11y": {
    "href": "/18-accessibility/forms-a11y/",
    "title": "Accessible Forms"
  },
  "18-accessibility.live-regions": {
    "href": "/18-accessibility/live-regions/",
    "title": "Live Regions"
  },
  "18-accessibility.accessible-components": {
    "href": "/18-accessibility/accessible-components/",
    "title": "Accessible Components"
  },
  "18-accessibility.a11y-testing": {
    "href": "/18-accessibility/a11y-testing/",
    "title": "Accessibility Testing"
  },
  "18-accessibility.a11y-in-react": {
    "href": "/18-accessibility/a11y-in-react/",
    "title": "Accessibility in React"
  },
  "18-accessibility.a11y-in-nextjs": {
    "href": "/18-accessibility/a11y-in-nextjs/",
    "title": "Accessibility in Next.js"
  },
  "19-deployment.docker": {
    "href": "/19-deployment/docker/",
    "title": "Docker"
  },
  "19-deployment.nginx": {
    "href": "/19-deployment/nginx/",
    "title": "Nginx"
  },
  "19-deployment.reverse-proxy": {
    "href": "/19-deployment/reverse-proxy/",
    "title": "Reverse Proxy"
  },
  "19-deployment.cdn-deployment": {
    "href": "/19-deployment/cdn-deployment/",
    "title": "CDN Deployment"
  },
  "19-deployment.ci-cd": {
    "href": "/19-deployment/ci-cd/",
    "title": "CI/CD"
  },
  "19-deployment.github-actions": {
    "href": "/19-deployment/github-actions/",
    "title": "GitHub Actions"
  },
  "19-deployment.vercel": {
    "href": "/19-deployment/vercel/",
    "title": "Vercel"
  },
  "19-deployment.netlify": {
    "href": "/19-deployment/netlify/",
    "title": "Netlify"
  },
  "19-deployment.aws-frontend": {
    "href": "/19-deployment/aws-frontend/",
    "title": "AWS for Frontend"
  },
  "19-deployment.cloudflare": {
    "href": "/19-deployment/cloudflare/",
    "title": "Cloudflare"
  },
  "19-deployment.environment-config": {
    "href": "/19-deployment/environment-config/",
    "title": "Environment Config"
  },
  "19-deployment.preview-deployments": {
    "href": "/19-deployment/preview-deployments/",
    "title": "Preview Deployments"
  },
  "19-deployment.rollback-strategies": {
    "href": "/19-deployment/rollback-strategies/",
    "title": "Rollback Strategies"
  },
  "20-observability.chrome-devtools": {
    "href": "/20-observability/chrome-devtools/",
    "title": "Chrome DevTools"
  },
  "20-observability.debugging-javascript": {
    "href": "/20-observability/debugging-javascript/",
    "title": "Debugging JavaScript"
  },
  "20-observability.debugging-network": {
    "href": "/20-observability/debugging-network/",
    "title": "Debugging Network"
  },
  "20-observability.debugging-performance": {
    "href": "/20-observability/debugging-performance/",
    "title": "Debugging Performance"
  },
  "20-observability.source-maps-debugging": {
    "href": "/20-observability/source-maps-debugging/",
    "title": "Source Maps Debugging"
  },
  "20-observability.logging": {
    "href": "/20-observability/logging/",
    "title": "Logging"
  },
  "20-observability.error-tracking": {
    "href": "/20-observability/error-tracking/",
    "title": "Error Tracking"
  },
  "20-observability.rum": {
    "href": "/20-observability/rum/",
    "title": "Real User Monitoring"
  },
  "20-observability.web-vitals-monitoring": {
    "href": "/20-observability/web-vitals-monitoring/",
    "title": "Web Vitals Monitoring"
  },
  "20-observability.tracing-frontend": {
    "href": "/20-observability/tracing-frontend/",
    "title": "Frontend Tracing"
  },
  "20-observability.feature-telemetry": {
    "href": "/20-observability/feature-telemetry/",
    "title": "Feature Telemetry"
  },
  "21-frontend-system-design.scaling-react-applications": {
    "href": "/21-frontend-system-design/scaling-react-applications/",
    "title": "Scaling React Applications"
  },
  "21-frontend-system-design.caching-strategies": {
    "href": "/21-frontend-system-design/caching-strategies/",
    "title": "Caching Strategies"
  },
  "21-frontend-system-design.optimistic-ui": {
    "href": "/21-frontend-system-design/optimistic-ui/",
    "title": "Optimistic UI"
  },
  "21-frontend-system-design.offline-first": {
    "href": "/21-frontend-system-design/offline-first/",
    "title": "Offline First"
  },
  "21-frontend-system-design.infinite-scroll": {
    "href": "/21-frontend-system-design/infinite-scroll/",
    "title": "Infinite Scroll"
  },
  "21-frontend-system-design.pagination": {
    "href": "/21-frontend-system-design/pagination/",
    "title": "Pagination"
  },
  "21-frontend-system-design.feature-flags": {
    "href": "/21-frontend-system-design/feature-flags/",
    "title": "Feature Flags"
  },
  "21-frontend-system-design.realtime-applications": {
    "href": "/21-frontend-system-design/realtime-applications/",
    "title": "Realtime Applications"
  },
  "21-frontend-system-design.search-ui": {
    "href": "/21-frontend-system-design/search-ui/",
    "title": "Search UI"
  },
  "21-frontend-system-design.upload-pipelines": {
    "href": "/21-frontend-system-design/upload-pipelines/",
    "title": "Upload Pipelines"
  },
  "21-frontend-system-design.multi-tenant-ui": {
    "href": "/21-frontend-system-design/multi-tenant-ui/",
    "title": "Multi-Tenant UI"
  },
  "21-frontend-system-design.internationalized-apps": {
    "href": "/21-frontend-system-design/internationalized-apps/",
    "title": "Internationalized Apps"
  },
  "21-frontend-system-design.designing-design-systems": {
    "href": "/21-frontend-system-design/designing-design-systems/",
    "title": "Designing Design Systems"
  },
  "22-design-patterns.mvc-mvp-mvvm": {
    "href": "/22-design-patterns/mvc-mvp-mvvm/",
    "title": "MVC, MVP, MVVM"
  },
  "22-design-patterns.container-presentational": {
    "href": "/22-design-patterns/container-presentational/",
    "title": "Container / Presentational"
  },
  "22-design-patterns.hooks-patterns": {
    "href": "/22-design-patterns/hooks-patterns/",
    "title": "Hooks Patterns"
  },
  "22-design-patterns.compound-components": {
    "href": "/22-design-patterns/compound-components/",
    "title": "Compound Components"
  },
  "22-design-patterns.render-props": {
    "href": "/22-design-patterns/render-props/",
    "title": "Render Props"
  },
  "22-design-patterns.hoc": {
    "href": "/22-design-patterns/hoc/",
    "title": "Higher-Order Components"
  },
  "22-design-patterns.provider-pattern": {
    "href": "/22-design-patterns/provider-pattern/",
    "title": "Provider Pattern"
  },
  "22-design-patterns.observer-pattern": {
    "href": "/22-design-patterns/observer-pattern/",
    "title": "Observer Pattern"
  },
  "22-design-patterns.module-pattern": {
    "href": "/22-design-patterns/module-pattern/",
    "title": "Module Pattern"
  },
  "22-design-patterns.factory-and-builder": {
    "href": "/22-design-patterns/factory-and-builder/",
    "title": "Factory and Builder"
  },
  "22-design-patterns.when-patterns-hurt": {
    "href": "/22-design-patterns/when-patterns-hurt/",
    "title": "When Patterns Hurt"
  },
  "23-pwa-and-offline.pwa-overview": {
    "href": "/23-pwa-and-offline/pwa-overview/",
    "title": "PWA Overview"
  },
  "23-pwa-and-offline.service-worker-lifecycle": {
    "href": "/23-pwa-and-offline/service-worker-lifecycle/",
    "title": "Service Worker Lifecycle"
  },
  "23-pwa-and-offline.caching-strategies-sw": {
    "href": "/23-pwa-and-offline/caching-strategies-sw/",
    "title": "Service Worker Caching Strategies"
  },
  "23-pwa-and-offline.background-sync": {
    "href": "/23-pwa-and-offline/background-sync/",
    "title": "Background Sync"
  },
  "23-pwa-and-offline.web-app-manifest": {
    "href": "/23-pwa-and-offline/web-app-manifest/",
    "title": "Web App Manifest"
  },
  "23-pwa-and-offline.installability": {
    "href": "/23-pwa-and-offline/installability/",
    "title": "Installability"
  },
  "23-pwa-and-offline.push-notifications": {
    "href": "/23-pwa-and-offline/push-notifications/",
    "title": "Push Notifications"
  },
  "23-pwa-and-offline.offline-ux": {
    "href": "/23-pwa-and-offline/offline-ux/",
    "title": "Offline UX"
  },
  "24-interview-preparation.how-to-answer": {
    "href": "/24-interview-preparation/how-to-answer/",
    "title": "How to Answer"
  },
  "24-interview-preparation.javascript-interview-questions": {
    "href": "/24-interview-preparation/javascript-interview-questions/",
    "title": "JavaScript Interview Questions"
  },
  "24-interview-preparation.browser-interview-questions": {
    "href": "/24-interview-preparation/browser-interview-questions/",
    "title": "Browser Interview Questions"
  },
  "24-interview-preparation.react-interview-questions": {
    "href": "/24-interview-preparation/react-interview-questions/",
    "title": "React Interview Questions"
  },
  "24-interview-preparation.nextjs-interview-questions": {
    "href": "/24-interview-preparation/nextjs-interview-questions/",
    "title": "Next.js Interview Questions"
  },
  "24-interview-preparation.network-interview-questions": {
    "href": "/24-interview-preparation/network-interview-questions/",
    "title": "Network Interview Questions"
  },
  "24-interview-preparation.css-interview-questions": {
    "href": "/24-interview-preparation/css-interview-questions/",
    "title": "CSS Interview Questions"
  },
  "24-interview-preparation.typescript-interview-questions": {
    "href": "/24-interview-preparation/typescript-interview-questions/",
    "title": "TypeScript Interview Questions"
  },
  "24-interview-preparation.performance-interview-questions": {
    "href": "/24-interview-preparation/performance-interview-questions/",
    "title": "Performance Interview Questions"
  },
  "24-interview-preparation.security-interview-questions": {
    "href": "/24-interview-preparation/security-interview-questions/",
    "title": "Security Interview Questions"
  },
  "24-interview-preparation.system-design-interview-questions": {
    "href": "/24-interview-preparation/system-design-interview-questions/",
    "title": "System Design Interview Questions"
  },
  "25-appendix.browser-compatibility": {
    "href": "/25-appendix/browser-compatibility/",
    "title": "Browser Compatibility"
  },
  "25-appendix.http-status-codes": {
    "href": "/25-appendix/http-status-codes/",
    "title": "HTTP Status Codes"
  },
  "25-appendix.mime-types": {
    "href": "/25-appendix/mime-types/",
    "title": "MIME Types"
  },
  "25-appendix.priority-hints-cheatsheet": {
    "href": "/25-appendix/priority-hints-cheatsheet/",
    "title": "Priority Hints Cheatsheet"
  },
  "25-appendix.glossary-export": {
    "href": "/25-appendix/glossary-export/",
    "title": "Glossary Export"
  },
  "25-appendix.curriculum-changelog": {
    "href": "/25-appendix/curriculum-changelog/",
    "title": "Curriculum Changelog"
  },
  "25-appendix.further-reading-policy": {
    "href": "/25-appendix/further-reading-policy/",
    "title": "Further Reading Policy"
  }
}

export function topicHrefById(id: string): string {
  return topicMap[id]?.href ?? `#missing-topic-${id}`
}

export function topicTitleById(id: string): string {
  return topicMap[id]?.title ?? id
}
