export type SeedTopic = {
  slug: string
  title: string
  difficulty?: 'beginner' | 'junior' | 'mid' | 'senior' | 'expert'
  reading?: number
  implementation?: number
  prerequisites?: string[]
  recommended_next?: string[]
  related?: string[]
  depends_on?: string[]
  tags?: string[]
  /** Nested path segments under module, default [slug] */
  segments?: string[]
  children?: SeedTopic[]
  advanced?: string[]
  beginner_path?: string
  perspective_of?: string[]
}

export type SeedModule = {
  id: string
  title: string
  description: string
  topics: SeedTopic[]
}

function t(
  slug: string,
  title: string,
  extras: Omit<SeedTopic, 'slug' | 'title'> = {},
): SeedTopic {
  return { slug, title, ...extras }
}

export const MODULES: SeedModule[] = [
  {
    id: '00-foundations',
    title: 'Foundations',
    description: 'How to read this handbook and orient yourself in the web stack',
    topics: [
      t('start-here', 'Start Here', { difficulty: 'beginner', reading: 15, tags: ['orientation'] }),
      t('how-the-web-works-map', 'How the Web Works Map', {
        difficulty: 'beginner',
        reading: 25,
        prerequisites: ['00-foundations.start-here'],
        tags: ['orientation', 'mental-model'],
      }),
      t('how-to-read-this-handbook', 'How to Read This Handbook', {
        difficulty: 'beginner',
        reading: 15,
        tags: ['orientation'],
      }),
      t('prerequisites-checklist', 'Prerequisites Checklist', {
        difficulty: 'beginner',
        reading: 10,
        tags: ['orientation'],
      }),
      t('conventions-used', 'Conventions Used', {
        difficulty: 'beginner',
        reading: 10,
        tags: ['orientation'],
      }),
    ],
  },
  {
    id: '01-computer-science',
    title: 'Computer Science Fundamentals',
    description: 'Bits, machines, runtimes, complexity, and core data structures',
    topics: [
      t('binary', 'Binary', { difficulty: 'beginner', reading: 25, tags: ['cs-fundamentals'] }),
      t('bits-and-bytes', 'Bits and Bytes', {
        difficulty: 'beginner',
        reading: 20,
        prerequisites: ['01-computer-science.binary'],
        tags: ['cs-fundamentals'],
      }),
      t('cpu', 'CPU', {
        difficulty: 'beginner',
        reading: 30,
        prerequisites: ['01-computer-science.bits-and-bytes'],
        tags: ['cs-fundamentals'],
      }),
      t('memory', 'Memory', {
        difficulty: 'beginner',
        reading: 35,
        prerequisites: ['01-computer-science.cpu'],
        tags: ['cs-fundamentals', 'memory'],
      }),
      t('stack', 'Stack', {
        difficulty: 'junior',
        reading: 25,
        prerequisites: ['01-computer-science.memory'],
        tags: ['cs-fundamentals', 'memory'],
      }),
      t('heap', 'Heap', {
        difficulty: 'junior',
        reading: 25,
        prerequisites: ['01-computer-science.memory'],
        tags: ['cs-fundamentals', 'memory'],
      }),
      t('process', 'Process', {
        difficulty: 'junior',
        reading: 30,
        prerequisites: ['01-computer-science.memory'],
        tags: ['cs-fundamentals', 'concurrency'],
      }),
      t('thread', 'Thread', {
        difficulty: 'junior',
        reading: 30,
        prerequisites: ['01-computer-science.process'],
        tags: ['cs-fundamentals', 'concurrency'],
      }),
      t('event-loop-cs', 'Event Loop (Runtime View)', {
        difficulty: 'mid',
        reading: 35,
        prerequisites: ['01-computer-science.thread'],
        tags: ['cs-fundamentals', 'async'],
        related: ['03-browser.event-loop', '06-javascript.event-loop-js'],
      }),
      t('compiler', 'Compiler', {
        difficulty: 'junior',
        reading: 35,
        prerequisites: ['01-computer-science.cpu'],
        tags: ['cs-fundamentals', 'compilers'],
      }),
      t('interpreter', 'Interpreter', {
        difficulty: 'junior',
        reading: 30,
        prerequisites: ['01-computer-science.compiler'],
        tags: ['cs-fundamentals', 'compilers'],
      }),
      t('runtime', 'Runtime', {
        difficulty: 'junior',
        reading: 30,
        prerequisites: ['01-computer-science.interpreter'],
        tags: ['cs-fundamentals'],
      }),
      t('garbage-collection', 'Garbage Collection', {
        difficulty: 'mid',
        reading: 40,
        prerequisites: ['01-computer-science.heap', '01-computer-science.runtime'],
        tags: ['cs-fundamentals', 'memory'],
      }),
      t('time-complexity', 'Time Complexity', {
        difficulty: 'junior',
        reading: 30,
        tags: ['cs-fundamentals', 'algorithms'],
      }),
      t('space-complexity', 'Space Complexity', {
        difficulty: 'junior',
        reading: 25,
        prerequisites: ['01-computer-science.time-complexity'],
        tags: ['cs-fundamentals', 'algorithms'],
      }),
      t('big-o', 'Big O', {
        difficulty: 'junior',
        reading: 35,
        prerequisites: ['01-computer-science.time-complexity', '01-computer-science.space-complexity'],
        tags: ['cs-fundamentals', 'algorithms', 'interview-frequent'],
      }),
      t('data-structures', 'Data Structures', {
        difficulty: 'junior',
        reading: 20,
        prerequisites: ['01-computer-science.big-o'],
        tags: ['cs-fundamentals', 'data-structures'],
        children: [
          t('array', 'Array', {
            difficulty: 'beginner',
            reading: 25,
            segments: ['data-structures', 'array'],
            tags: ['data-structures'],
          }),
          t('linked-list', 'Linked List', {
            difficulty: 'junior',
            reading: 25,
            segments: ['data-structures', 'linked-list'],
            tags: ['data-structures'],
          }),
          t('stack-ds', 'Stack (Data Structure)', {
            difficulty: 'junior',
            reading: 20,
            segments: ['data-structures', 'stack-ds'],
            tags: ['data-structures'],
          }),
          t('queue', 'Queue', {
            difficulty: 'junior',
            reading: 20,
            segments: ['data-structures', 'queue'],
            tags: ['data-structures'],
          }),
          t('hash-table', 'Hash Table', {
            difficulty: 'junior',
            reading: 35,
            segments: ['data-structures', 'hash-table'],
            tags: ['data-structures', 'interview-frequent'],
          }),
          t('tree', 'Tree', {
            difficulty: 'mid',
            reading: 40,
            segments: ['data-structures', 'tree'],
            tags: ['data-structures'],
          }),
          t('graph', 'Graph', {
            difficulty: 'mid',
            reading: 40,
            segments: ['data-structures', 'graph'],
            tags: ['data-structures'],
          }),
        ],
      }),
      t('algorithms', 'Algorithms', {
        difficulty: 'junior',
        reading: 20,
        prerequisites: ['01-computer-science.data-structures'],
        tags: ['cs-fundamentals', 'algorithms'],
        children: [
          t('searching', 'Searching', {
            difficulty: 'junior',
            reading: 30,
            segments: ['algorithms', 'searching'],
            tags: ['algorithms'],
          }),
          t('sorting', 'Sorting', {
            difficulty: 'junior',
            reading: 40,
            segments: ['algorithms', 'sorting'],
            tags: ['algorithms', 'interview-frequent'],
          }),
          t('recursion', 'Recursion', {
            difficulty: 'junior',
            reading: 30,
            segments: ['algorithms', 'recursion'],
            tags: ['algorithms'],
          }),
          t('dynamic-programming-intro', 'Dynamic Programming Intro', {
            difficulty: 'mid',
            reading: 45,
            segments: ['algorithms', 'dynamic-programming-intro'],
            tags: ['algorithms'],
          }),
        ],
      }),
    ],
  },
  {
    id: '02-internet',
    title: 'Internet',
    description: 'Networks, DNS, transport, HTTP family, and web auth primitives',
    topics: [
      t('what-is-the-internet', 'What is the Internet', { difficulty: 'beginner', reading: 25, tags: ['networking'] }),
      t('client', 'Client', { difficulty: 'beginner', reading: 15, tags: ['networking'] }),
      t('server', 'Server', { difficulty: 'beginner', reading: 15, tags: ['networking'] }),
      t('isp', 'ISP', { difficulty: 'beginner', reading: 15, tags: ['networking'] }),
      t('router', 'Router', { difficulty: 'beginner', reading: 20, tags: ['networking'] }),
      t('switch', 'Switch', { difficulty: 'beginner', reading: 15, tags: ['networking'] }),
      t('dns', 'DNS', { difficulty: 'junior', reading: 40, tags: ['networking', 'interview-frequent'] }),
      t('domain', 'Domain', { difficulty: 'beginner', reading: 20, tags: ['networking'] }),
      t('ip', 'IP', { difficulty: 'junior', reading: 25, tags: ['networking'] }),
      t('ipv4', 'IPv4', { difficulty: 'junior', reading: 25, prerequisites: ['02-internet.ip'], tags: ['networking'] }),
      t('ipv6', 'IPv6', { difficulty: 'junior', reading: 25, prerequisites: ['02-internet.ip'], tags: ['networking'] }),
      t('tcp', 'TCP', { difficulty: 'mid', reading: 40, tags: ['networking', 'interview-frequent'] }),
      t('udp', 'UDP', { difficulty: 'mid', reading: 30, tags: ['networking'] }),
      t('http', 'HTTP', { difficulty: 'junior', reading: 45, prerequisites: ['02-internet.tcp'], tags: ['networking', 'http', 'interview-frequent'] }),
      t('https', 'HTTPS', { difficulty: 'junior', reading: 35, prerequisites: ['02-internet.http'], tags: ['networking', 'security'] }),
      t('ssl', 'SSL', { difficulty: 'mid', reading: 25, prerequisites: ['02-internet.https'], tags: ['security', 'networking'] }),
      t('tls', 'TLS', { difficulty: 'mid', reading: 40, prerequisites: ['02-internet.https'], tags: ['security', 'networking', 'interview-frequent'] }),
      t('ssh', 'SSH', { difficulty: 'mid', reading: 25, tags: ['networking', 'security'] }),
      t('websocket', 'WebSocket', { difficulty: 'mid', reading: 35, prerequisites: ['02-internet.http'], tags: ['networking', 'realtime'] }),
      t('sse', 'Server-Sent Events', { difficulty: 'mid', reading: 25, prerequisites: ['02-internet.http'], tags: ['networking', 'realtime'] }),
      t('http2', 'HTTP/2', { difficulty: 'mid', reading: 35, prerequisites: ['02-internet.http'], tags: ['http', 'networking'] }),
      t('http3', 'HTTP/3', { difficulty: 'senior', reading: 35, prerequisites: ['02-internet.http2'], tags: ['http', 'networking'] }),
      t('quic', 'QUIC', { difficulty: 'senior', reading: 40, prerequisites: ['02-internet.udp', '02-internet.tls'], tags: ['networking'] }),
      t('cookies', 'Cookies', { difficulty: 'junior', reading: 35, prerequisites: ['02-internet.http'], tags: ['http', 'security', 'interview-frequent'] }),
      t('sessions', 'Sessions', { difficulty: 'junior', reading: 30, prerequisites: ['02-internet.cookies'], tags: ['http', 'security'] }),
      t('authentication', 'Authentication', { difficulty: 'mid', reading: 40, tags: ['security', 'auth'] }),
      t('authorization', 'Authorization', { difficulty: 'mid', reading: 35, prerequisites: ['02-internet.authentication'], tags: ['security', 'auth'] }),
      t('rest', 'REST', { difficulty: 'junior', reading: 35, prerequisites: ['02-internet.http'], tags: ['api', 'http'] }),
      t('graphql', 'GraphQL', { difficulty: 'mid', reading: 40, prerequisites: ['02-internet.http'], tags: ['api'] }),
      t('http-caching', 'HTTP Caching', { difficulty: 'mid', reading: 45, prerequisites: ['02-internet.http'], tags: ['http', 'caching', 'performance', 'interview-frequent'] }),
      t('cdn-basics', 'CDN Basics', { difficulty: 'junior', reading: 30, prerequisites: ['02-internet.http-caching'], tags: ['networking', 'caching'] }),
      t('load-balancing-basics', 'Load Balancing Basics', { difficulty: 'mid', reading: 30, tags: ['networking'] }),
    ],
  },
  {
    id: '03-browser',
    title: 'Browser',
    description: 'Browser architecture, rendering pipeline, event loop, and memory',
    topics: [
      t('browser-architecture', 'Browser Architecture', { difficulty: 'junior', reading: 40, tags: ['browser-internals'] }),
      t('multi-process-model', 'Multi-Process Model', { difficulty: 'mid', reading: 35, prerequisites: ['03-browser.browser-architecture', '01-computer-science.process'], tags: ['browser-internals'] }),
      t('rendering-engine', 'Rendering Engine', { difficulty: 'mid', reading: 40, prerequisites: ['03-browser.browser-architecture'], tags: ['browser-internals', 'rendering'] }),
      t('javascript-engine', 'JavaScript Engine', { difficulty: 'mid', reading: 40, prerequisites: ['03-browser.browser-architecture', '01-computer-science.runtime'], tags: ['browser-internals', 'javascript-engine'] }),
      t('v8', 'V8', { difficulty: 'senior', reading: 50, prerequisites: ['03-browser.javascript-engine'], tags: ['javascript-engine', 'v8'] }),
      t('spidermonkey', 'SpiderMonkey', { difficulty: 'senior', reading: 30, prerequisites: ['03-browser.javascript-engine'], tags: ['javascript-engine'] }),
      t('javascriptcore', 'JavaScriptCore', { difficulty: 'senior', reading: 30, prerequisites: ['03-browser.javascript-engine'], tags: ['javascript-engine'] }),
      t('parsing-html', 'Parsing HTML', { difficulty: 'mid', reading: 35, prerequisites: ['03-browser.rendering-engine'], tags: ['browser-internals', 'html'] }),
      t('parsing-css', 'Parsing CSS', { difficulty: 'mid', reading: 30, prerequisites: ['03-browser.rendering-engine'], tags: ['browser-internals', 'css'] }),
      t('dom', 'DOM', { difficulty: 'junior', reading: 35, prerequisites: ['03-browser.parsing-html'], tags: ['browser-internals', 'html', 'interview-frequent'] }),
      t('cssom', 'CSSOM', { difficulty: 'mid', reading: 30, prerequisites: ['03-browser.parsing-css'], tags: ['browser-internals', 'css'] }),
      t('render-tree', 'Render Tree', { difficulty: 'mid', reading: 30, prerequisites: ['03-browser.dom', '03-browser.cssom'], tags: ['browser-internals', 'rendering'] }),
      t('layout', 'Layout', { difficulty: 'mid', reading: 35, prerequisites: ['03-browser.render-tree'], tags: ['browser-internals', 'rendering'] }),
      t('paint', 'Paint', { difficulty: 'mid', reading: 30, prerequisites: ['03-browser.layout'], tags: ['browser-internals', 'rendering'] }),
      t('composite', 'Composite', { difficulty: 'mid', reading: 35, prerequisites: ['03-browser.paint'], tags: ['browser-internals', 'rendering', 'performance'] }),
      t('gpu', 'GPU', { difficulty: 'senior', reading: 30, prerequisites: ['03-browser.composite'], tags: ['browser-internals', 'rendering'] }),
      t('reflow', 'Reflow', { difficulty: 'mid', reading: 30, prerequisites: ['03-browser.layout'], tags: ['browser-internals', 'performance', 'interview-frequent'] }),
      t('repaint', 'Repaint', { difficulty: 'mid', reading: 25, prerequisites: ['03-browser.paint'], tags: ['browser-internals', 'performance'] }),
      t('critical-rendering-path', 'Critical Rendering Path', { difficulty: 'mid', reading: 45, prerequisites: ['03-browser.render-tree', '03-browser.layout', '03-browser.paint'], tags: ['browser-internals', 'performance', 'interview-frequent'] }),
      t('call-stack', 'Call Stack', { difficulty: 'junior', reading: 25, prerequisites: ['01-computer-science.stack'], tags: ['browser-internals', 'javascript', 'async'] }),
      t('task-queue', 'Task Queue', { difficulty: 'mid', reading: 30, prerequisites: ['03-browser.call-stack'], tags: ['browser-internals', 'async'] }),
      t('event-loop', 'Event Loop', { difficulty: 'mid', reading: 45, prerequisites: ['03-browser.call-stack', '03-browser.task-queue'], related: ['01-computer-science.event-loop-cs', '06-javascript.event-loop-js'], tags: ['browser-internals', 'async', 'interview-frequent'] }),
      t('microtasks', 'Microtasks', { difficulty: 'mid', reading: 35, prerequisites: ['03-browser.event-loop'], tags: ['browser-internals', 'async', 'interview-frequent'] }),
      t('macrotasks', 'Macrotasks', { difficulty: 'mid', reading: 30, prerequisites: ['03-browser.event-loop'], tags: ['browser-internals', 'async'] }),
      t('memory-management', 'Memory Management', { difficulty: 'mid', reading: 40, prerequisites: ['01-computer-science.heap'], tags: ['browser-internals', 'memory'] }),
      t('garbage-collection-browser', 'Garbage Collection in the Browser', { difficulty: 'senior', reading: 40, prerequisites: ['03-browser.memory-management', '01-computer-science.garbage-collection'], tags: ['browser-internals', 'memory', 'v8'] }),
      t('devtools-rendering-panel', 'DevTools Rendering Panel', { difficulty: 'mid', reading: 25, prerequisites: ['03-browser.critical-rendering-path'], related: ['20-observability.chrome-devtools'], tags: ['devtools', 'rendering'] }),
    ],
  },
  {
    id: '04-html',
    title: 'HTML',
    description: 'Document semantics, forms, SEO metadata, and resource hints',
    topics: [
      t('semantic-html', 'Semantic HTML', { difficulty: 'beginner', reading: 35, tags: ['html', 'a11y', 'seo'] }),
      t('document-structure', 'Document Structure', { difficulty: 'beginner', reading: 25, tags: ['html'] }),
      t('forms', 'Forms', { difficulty: 'junior', reading: 40, tags: ['html', 'a11y'] }),
      t('media-elements', 'Media Elements', { difficulty: 'junior', reading: 30, tags: ['html'] }),
      t('metadata', 'Metadata', { difficulty: 'junior', reading: 25, tags: ['html', 'seo'] }),
      t('seo-basics', 'SEO Basics', { difficulty: 'junior', reading: 35, prerequisites: ['04-html.semantic-html', '04-html.metadata'], tags: ['seo', 'html'] }),
      t('scripts', 'Scripts', { difficulty: 'junior', reading: 30, tags: ['html', 'javascript', 'performance'] }),
      t('defer', 'defer', { difficulty: 'junior', reading: 20, prerequisites: ['04-html.scripts'], tags: ['html', 'performance'] }),
      t('async', 'async', { difficulty: 'junior', reading: 20, prerequisites: ['04-html.scripts'], tags: ['html', 'performance'] }),
      t('module-scripts', 'Module Scripts', { difficulty: 'junior', reading: 25, prerequisites: ['04-html.scripts'], tags: ['html', 'javascript'] }),
      t('preload', 'preload', { difficulty: 'mid', reading: 25, tags: ['html', 'performance'] }),
      t('prefetch', 'prefetch', { difficulty: 'mid', reading: 20, tags: ['html', 'performance'] }),
      t('preconnect', 'preconnect', { difficulty: 'mid', reading: 20, tags: ['html', 'performance', 'networking'] }),
      t('modulepreload', 'modulepreload', { difficulty: 'mid', reading: 20, tags: ['html', 'performance'] }),
      t('templates-and-slots', 'Templates and Slots', { difficulty: 'mid', reading: 25, related: ['09-browser-apis.web-components'], tags: ['html', 'web-components'] }),
    ],
  },
  {
    id: '05-css',
    title: 'CSS',
    description: 'Cascade, layout systems, responsive design, and compositing',
    topics: [
      t('cascade', 'Cascade', { difficulty: 'junior', reading: 35, tags: ['css', 'interview-frequent'] }),
      t('specificity', 'Specificity', { difficulty: 'junior', reading: 30, prerequisites: ['05-css.cascade'], tags: ['css', 'interview-frequent'] }),
      t('inheritance', 'Inheritance', { difficulty: 'beginner', reading: 20, tags: ['css'] }),
      t('box-model', 'Box Model', { difficulty: 'beginner', reading: 30, tags: ['css', 'interview-frequent'] }),
      t('positioning', 'Positioning', { difficulty: 'junior', reading: 35, prerequisites: ['05-css.box-model'], tags: ['css'] }),
      t('flexbox', 'Flexbox', { difficulty: 'junior', reading: 40, tags: ['css', 'layout'] }),
      t('grid', 'Grid', { difficulty: 'junior', reading: 45, tags: ['css', 'layout'] }),
      t('responsive-design', 'Responsive Design', { difficulty: 'junior', reading: 35, tags: ['css', 'responsive'] }),
      t('media-queries', 'Media Queries', { difficulty: 'junior', reading: 30, prerequisites: ['05-css.responsive-design'], tags: ['css', 'responsive'] }),
      t('container-queries', 'Container Queries', { difficulty: 'mid', reading: 30, prerequisites: ['05-css.media-queries'], tags: ['css', 'responsive'] }),
      t('animations', 'Animations', { difficulty: 'mid', reading: 35, tags: ['css', 'animation'] }),
      t('transitions', 'Transitions', { difficulty: 'junior', reading: 25, tags: ['css', 'animation'] }),
      t('transforms', 'Transforms', { difficulty: 'junior', reading: 25, tags: ['css', 'animation', 'performance'] }),
      t('compositing', 'Compositing', { difficulty: 'mid', reading: 35, prerequisites: ['03-browser.composite'], tags: ['css', 'performance', 'rendering'] }),
      t('containment', 'Containment', { difficulty: 'senior', reading: 30, tags: ['css', 'performance'] }),
      t('layers', 'Layers', { difficulty: 'mid', reading: 25, tags: ['css'] }),
      t('modern-css', 'Modern CSS', { difficulty: 'mid', reading: 40, tags: ['css'] }),
      t('css-architecture', 'CSS Architecture', { difficulty: 'mid', reading: 35, related: ['15-architecture.design-systems'], tags: ['css', 'architecture'] }),
    ],
  },
  {
    id: '06-javascript',
    title: 'JavaScript',
    description: 'Language semantics from values and scope through async and metaprogramming',
    topics: [
      t('variables', 'Variables', { difficulty: 'beginner', reading: 25, tags: ['javascript'] }),
      t('types-and-values', 'Types and Values', { difficulty: 'beginner', reading: 35, tags: ['javascript', 'interview-frequent'] }),
      t('scope', 'Scope', { difficulty: 'junior', reading: 35, tags: ['javascript', 'interview-frequent'] }),
      t('closures', 'Closures', { difficulty: 'junior', reading: 40, prerequisites: ['06-javascript.scope'], tags: ['javascript', 'interview-frequent'] }),
      t('hoisting', 'Hoisting', { difficulty: 'junior', reading: 30, prerequisites: ['06-javascript.variables', '06-javascript.scope'], tags: ['javascript', 'interview-frequent'] }),
      t('execution-context', 'Execution Context', { difficulty: 'mid', reading: 40, prerequisites: ['06-javascript.scope'], tags: ['javascript', 'javascript-engine'] }),
      t('lexical-environment', 'Lexical Environment', { difficulty: 'mid', reading: 35, prerequisites: ['06-javascript.execution-context'], tags: ['javascript'] }),
      t('prototype', 'Prototype', { difficulty: 'mid', reading: 35, tags: ['javascript', 'interview-frequent'] }),
      t('prototype-chain', 'Prototype Chain', { difficulty: 'mid', reading: 35, prerequisites: ['06-javascript.prototype'], tags: ['javascript', 'interview-frequent'] }),
      t('this', 'this', { difficulty: 'mid', reading: 40, tags: ['javascript', 'interview-frequent'] }),
      t('classes', 'Classes', { difficulty: 'junior', reading: 35, prerequisites: ['06-javascript.prototype'], tags: ['javascript'] }),
      t('functions', 'Functions', { difficulty: 'beginner', reading: 30, tags: ['javascript'] }),
      t('objects', 'Objects', { difficulty: 'beginner', reading: 30, tags: ['javascript'] }),
      t('arrays', 'Arrays', { difficulty: 'beginner', reading: 30, tags: ['javascript'] }),
      t('modules', 'Modules', { difficulty: 'junior', reading: 25, tags: ['javascript'] }),
      t('es-modules', 'ES Modules', { difficulty: 'junior', reading: 35, prerequisites: ['06-javascript.modules'], tags: ['javascript'] }),
      t('commonjs', 'CommonJS', { difficulty: 'junior', reading: 25, prerequisites: ['06-javascript.modules'], tags: ['javascript', 'nodejs'] }),
      t('async-programming', 'Async Programming', { difficulty: 'junior', reading: 35, tags: ['javascript', 'async'] }),
      t('event-loop-js', 'Event Loop (JavaScript View)', { difficulty: 'mid', reading: 40, prerequisites: ['06-javascript.execution-context'], related: ['03-browser.event-loop', '01-computer-science.event-loop-cs'], perspective_of: ['03-browser.event-loop'], tags: ['javascript', 'async', 'interview-frequent'] }),
      t('promise', 'Promise', { difficulty: 'junior', reading: 40, prerequisites: ['06-javascript.async-programming'], tags: ['javascript', 'async', 'interview-frequent'] }),
      t('async-await', 'Async/Await', { difficulty: 'junior', reading: 35, prerequisites: ['06-javascript.promise'], tags: ['javascript', 'async'] }),
      t('generator', 'Generator', { difficulty: 'mid', reading: 35, tags: ['javascript'] }),
      t('iterator', 'Iterator', { difficulty: 'mid', reading: 30, tags: ['javascript'] }),
      t('fetch-api', 'Fetch API', { difficulty: 'junior', reading: 35, prerequisites: ['06-javascript.promise', '02-internet.http'], tags: ['javascript', 'networking'] }),
      t('abortcontroller', 'AbortController', { difficulty: 'mid', reading: 25, prerequisites: ['06-javascript.fetch-api'], tags: ['javascript', 'networking'] }),
      t('proxy', 'Proxy', { difficulty: 'senior', reading: 35, tags: ['javascript'] }),
      t('reflect', 'Reflect', { difficulty: 'senior', reading: 25, related: ['06-javascript.proxy'], tags: ['javascript'] }),
      t('symbols', 'Symbols', { difficulty: 'mid', reading: 25, tags: ['javascript'] }),
      t('weakmap', 'WeakMap', { difficulty: 'mid', reading: 25, tags: ['javascript', 'memory'] }),
      t('weakset', 'WeakSet', { difficulty: 'mid', reading: 20, tags: ['javascript', 'memory'] }),
      t('error-handling', 'Error Handling', { difficulty: 'junior', reading: 30, tags: ['javascript'] }),
      t('strict-mode', 'Strict Mode', { difficulty: 'junior', reading: 20, tags: ['javascript'] }),
      t('memory-and-references', 'Memory and References', { difficulty: 'mid', reading: 35, prerequisites: ['01-computer-science.stack', '01-computer-science.heap'], tags: ['javascript', 'memory'] }),
    ],
  },
  {
    id: '07-typescript',
    title: 'TypeScript',
    description: 'Types as a compile-time system on top of JavaScript',
    topics: [
      t('types', 'Types', { difficulty: 'junior', reading: 35, prerequisites: ['06-javascript.types-and-values'], tags: ['typescript'] }),
      t('interfaces', 'Interfaces', { difficulty: 'junior', reading: 30, tags: ['typescript'] }),
      t('type-vs-interface', 'Type vs Interface', { difficulty: 'junior', reading: 25, prerequisites: ['07-typescript.types', '07-typescript.interfaces'], tags: ['typescript', 'interview-frequent'] }),
      t('generics', 'Generics', { difficulty: 'mid', reading: 40, prerequisites: ['07-typescript.types'], tags: ['typescript', 'interview-frequent'] }),
      t('utility-types', 'Utility Types', { difficulty: 'mid', reading: 35, prerequisites: ['07-typescript.generics'], tags: ['typescript'] }),
      t('type-inference', 'Type Inference', { difficulty: 'junior', reading: 30, tags: ['typescript'] }),
      t('advanced-types', 'Advanced Types', { difficulty: 'senior', reading: 45, prerequisites: ['07-typescript.generics'], tags: ['typescript'] }),
      t('declaration-files', 'Declaration Files', { difficulty: 'mid', reading: 30, tags: ['typescript'] }),
      t('tsconfig', 'tsconfig', { difficulty: 'mid', reading: 35, tags: ['typescript'] }),
      t('compiler', 'TypeScript Compiler', { difficulty: 'mid', reading: 35, prerequisites: ['01-computer-science.compiler'], tags: ['typescript', 'compilers'] }),
      t('type-narrowing', 'Type Narrowing', { difficulty: 'mid', reading: 30, tags: ['typescript'] }),
      t('satisfies', 'satisfies', { difficulty: 'mid', reading: 20, tags: ['typescript'] }),
      t('enums-and-alternatives', 'Enums and Alternatives', { difficulty: 'mid', reading: 25, tags: ['typescript'] }),
      t('typescript-with-react', 'TypeScript with React', { difficulty: 'mid', reading: 40, related: ['10-react.components'], tags: ['typescript', 'react'] }),
    ],
  },
  {
    id: '08-jsx-and-react-runtime',
    title: 'JSX and React Runtime',
    description: 'JSX transforms, Virtual DOM, Fiber, and reconciliation before the React API surface',
    topics: [
      t('jsx', 'JSX', { difficulty: 'junior', reading: 30, prerequisites: ['06-javascript.functions'], tags: ['react', 'jsx'] }),
      t('babel', 'Babel', { difficulty: 'mid', reading: 35, tags: ['compilers', 'javascript'] }),
      t('ast', 'AST', { difficulty: 'mid', reading: 35, prerequisites: ['01-computer-science.compiler'], tags: ['compilers'] }),
      t('jsx-transform', 'JSX Transform', { difficulty: 'mid', reading: 30, prerequisites: ['08-jsx-and-react-runtime.jsx', '08-jsx-and-react-runtime.ast'], tags: ['react', 'jsx'] }),
      t('react-createelement', 'React.createElement', { difficulty: 'junior', reading: 25, prerequisites: ['08-jsx-and-react-runtime.jsx-transform'], tags: ['react'] }),
      t('virtual-dom', 'Virtual DOM', { difficulty: 'mid', reading: 40, prerequisites: ['08-jsx-and-react-runtime.react-createelement', '03-browser.dom'], tags: ['react', 'interview-frequent'] }),
      t('fiber', 'Fiber', { difficulty: 'senior', reading: 50, prerequisites: ['08-jsx-and-react-runtime.virtual-dom'], tags: ['react', 'react-internals'] }),
      t('reconciliation', 'Reconciliation', { difficulty: 'mid', reading: 40, prerequisites: ['08-jsx-and-react-runtime.fiber'], tags: ['react', 'interview-frequent'] }),
      t('diffing-algorithm', 'Diffing Algorithm', { difficulty: 'mid', reading: 35, prerequisites: ['08-jsx-and-react-runtime.reconciliation'], tags: ['react'] }),
      t('keys', 'Keys', { difficulty: 'junior', reading: 25, prerequisites: ['08-jsx-and-react-runtime.diffing-algorithm'], tags: ['react', 'interview-frequent'] }),
      t('fragments', 'Fragments', { difficulty: 'junior', reading: 15, tags: ['react'] }),
    ],
  },
  {
    id: '09-browser-apis',
    title: 'Browser APIs',
    description: 'Storage, observers, workers, and platform APIs',
    topics: [
      t('localstorage', 'localStorage', { difficulty: 'beginner', reading: 20, tags: ['browser-apis', 'storage'] }),
      t('sessionstorage', 'sessionStorage', { difficulty: 'beginner', reading: 15, tags: ['browser-apis', 'storage'] }),
      t('indexeddb', 'IndexedDB', { difficulty: 'mid', reading: 40, tags: ['browser-apis', 'storage'] }),
      t('cache-storage', 'Cache Storage', { difficulty: 'mid', reading: 30, tags: ['browser-apis', 'storage', 'pwa'] }),
      t('history-api', 'History API', { difficulty: 'junior', reading: 25, tags: ['browser-apis', 'routing'] }),
      t('clipboard-api', 'Clipboard API', { difficulty: 'junior', reading: 20, tags: ['browser-apis'] }),
      t('intersection-observer', 'Intersection Observer', { difficulty: 'mid', reading: 30, tags: ['browser-apis', 'performance'] }),
      t('mutation-observer', 'Mutation Observer', { difficulty: 'mid', reading: 25, tags: ['browser-apis'] }),
      t('resize-observer', 'Resize Observer', { difficulty: 'mid', reading: 20, tags: ['browser-apis'] }),
      t('broadcast-channel', 'Broadcast Channel', { difficulty: 'mid', reading: 20, tags: ['browser-apis'] }),
      t('web-workers', 'Web Workers', { difficulty: 'mid', reading: 40, prerequisites: ['01-computer-science.thread'], tags: ['browser-apis', 'concurrency', 'performance'] }),
      t('service-workers', 'Service Workers', { difficulty: 'mid', reading: 40, related: ['23-pwa-and-offline.service-worker-lifecycle'], tags: ['browser-apis', 'pwa'] }),
      t('notifications', 'Notifications', { difficulty: 'junior', reading: 20, tags: ['browser-apis'] }),
      t('geolocation', 'Geolocation', { difficulty: 'junior', reading: 15, tags: ['browser-apis'] }),
      t('web-sockets-api', 'WebSocket API', { difficulty: 'mid', reading: 25, prerequisites: ['02-internet.websocket'], tags: ['browser-apis', 'realtime'] }),
      t('streams-api', 'Streams API', { difficulty: 'senior', reading: 35, tags: ['browser-apis'] }),
      t('file-api', 'File API', { difficulty: 'junior', reading: 25, tags: ['browser-apis'] }),
      t('web-components', 'Web Components', { difficulty: 'mid', reading: 35, tags: ['browser-apis', 'web-components'] }),
      t('custom-elements', 'Custom Elements', { difficulty: 'mid', reading: 30, prerequisites: ['09-browser-apis.web-components'], tags: ['web-components'] }),
      t('shadow-dom', 'Shadow DOM', { difficulty: 'mid', reading: 30, prerequisites: ['09-browser-apis.web-components'], tags: ['web-components'] }),
    ],
  },
  {
    id: '10-react',
    title: 'React',
    description: 'React as a UI runtime: components, hooks, concurrent features, and compiler',
    topics: [
      t('philosophy', 'React Philosophy', { difficulty: 'junior', reading: 25, tags: ['react'] }),
      t('components', 'Components', { difficulty: 'beginner', reading: 30, prerequisites: ['08-jsx-and-react-runtime.jsx'], tags: ['react'] }),
      t('props', 'Props', { difficulty: 'beginner', reading: 25, prerequisites: ['10-react.components'], tags: ['react'] }),
      t('state', 'State', { difficulty: 'junior', reading: 35, prerequisites: ['10-react.components'], tags: ['react', 'interview-frequent'] }),
      t('hooks', 'Hooks', { difficulty: 'junior', reading: 35, prerequisites: ['10-react.state'], tags: ['react'] }),
      t('rules-of-hooks', 'Rules of Hooks', { difficulty: 'junior', reading: 25, prerequisites: ['10-react.hooks'], tags: ['react', 'interview-frequent'] }),
      t('context', 'Context', { difficulty: 'junior', reading: 35, prerequisites: ['10-react.hooks'], tags: ['react', 'state'] }),
      t('reducer', 'Reducer', { difficulty: 'junior', reading: 30, prerequisites: ['10-react.hooks'], tags: ['react', 'state'] }),
      t('memoization', 'Memoization in React', { difficulty: 'mid', reading: 30, tags: ['react', 'performance'] }),
      t('react-memo', 'React.memo', { difficulty: 'mid', reading: 25, prerequisites: ['10-react.memoization'], tags: ['react', 'performance'] }),
      t('usememo', 'useMemo', { difficulty: 'mid', reading: 25, prerequisites: ['10-react.memoization'], tags: ['react', 'performance'] }),
      t('usecallback', 'useCallback', { difficulty: 'mid', reading: 25, prerequisites: ['10-react.memoization'], tags: ['react', 'performance'] }),
      t('useref', 'useRef', { difficulty: 'junior', reading: 25, prerequisites: ['10-react.hooks'], tags: ['react'] }),
      t('useeffect', 'useEffect', { difficulty: 'junior', reading: 45, prerequisites: ['10-react.hooks', '03-browser.event-loop'], tags: ['react', 'interview-frequent'] }),
      t('uselayouteffect', 'useLayoutEffect', { difficulty: 'mid', reading: 30, prerequisites: ['10-react.useeffect'], tags: ['react'] }),
      t('useimperativehandle', 'useImperativeHandle', { difficulty: 'mid', reading: 20, prerequisites: ['10-react.useref'], tags: ['react'] }),
      t('useid', 'useId', { difficulty: 'junior', reading: 15, tags: ['react', 'a11y'] }),
      t('use', 'use', { difficulty: 'mid', reading: 30, tags: ['react'] }),
      t('suspense', 'Suspense', { difficulty: 'mid', reading: 40, tags: ['react'] }),
      t('lazy-loading', 'Lazy Loading', { difficulty: 'junior', reading: 25, prerequisites: ['10-react.suspense'], tags: ['react', 'performance'] }),
      t('error-boundaries', 'Error Boundaries', { difficulty: 'mid', reading: 30, tags: ['react'] }),
      t('portals', 'Portals', { difficulty: 'junior', reading: 20, tags: ['react'] }),
      t('concurrent-rendering', 'Concurrent Rendering', { difficulty: 'senior', reading: 45, prerequisites: ['08-jsx-and-react-runtime.fiber'], tags: ['react', 'react-internals'] }),
      t('transitions', 'Transitions', { difficulty: 'mid', reading: 30, prerequisites: ['10-react.concurrent-rendering'], tags: ['react'] }),
      t('deferred-value', 'useDeferredValue', { difficulty: 'mid', reading: 25, prerequisites: ['10-react.concurrent-rendering'], tags: ['react'] }),
      t('strict-mode', 'Strict Mode', { difficulty: 'junior', reading: 25, tags: ['react'] }),
      t('react-compiler', 'React Compiler', { difficulty: 'senior', reading: 40, tags: ['react', 'compilers', 'performance'] }),
      t('server-components-overview', 'Server Components Overview', { difficulty: 'mid', reading: 30, related: ['11-nextjs.server-components'], tags: ['react', 'rsc'] }),
      t('effects-vs-events', 'Effects vs Events', { difficulty: 'mid', reading: 30, prerequisites: ['10-react.useeffect'], tags: ['react'] }),
    ],
  },
  {
    id: '11-nextjs',
    title: 'Next.js',
    description: 'App Router, server components, caching, streaming, and edge runtimes',
    topics: [
      t('app-router', 'App Router', { difficulty: 'mid', reading: 40, prerequisites: ['10-react.components'], tags: ['nextjs'] }),
      t('pages-router', 'Pages Router', { difficulty: 'junior', reading: 30, tags: ['nextjs'] }),
      t('routing', 'Routing', { difficulty: 'junior', reading: 30, prerequisites: ['11-nextjs.app-router'], tags: ['nextjs', 'routing'] }),
      t('layouts', 'Layouts', { difficulty: 'junior', reading: 25, prerequisites: ['11-nextjs.app-router'], tags: ['nextjs'] }),
      t('nested-layouts', 'Nested Layouts', { difficulty: 'mid', reading: 25, prerequisites: ['11-nextjs.layouts'], tags: ['nextjs'] }),
      t('templates', 'Templates', { difficulty: 'mid', reading: 20, prerequisites: ['11-nextjs.layouts'], tags: ['nextjs'] }),
      t('loading-ui', 'Loading UI', { difficulty: 'junior', reading: 20, tags: ['nextjs'] }),
      t('error-ui', 'Error UI', { difficulty: 'junior', reading: 20, tags: ['nextjs'] }),
      t('metadata', 'Metadata', { difficulty: 'junior', reading: 25, tags: ['nextjs', 'seo'] }),
      t('route-handlers', 'Route Handlers', { difficulty: 'mid', reading: 30, tags: ['nextjs', 'api'] }),
      t('middleware', 'Middleware', { difficulty: 'mid', reading: 35, tags: ['nextjs'] }),
      t('edge-runtime', 'Edge Runtime', { difficulty: 'mid', reading: 30, tags: ['nextjs', 'edge'] }),
      t('node-runtime', 'Node Runtime', { difficulty: 'mid', reading: 25, tags: ['nextjs', 'nodejs'] }),
      t('image-optimization', 'Image Optimization', { difficulty: 'junior', reading: 30, tags: ['nextjs', 'performance'] }),
      t('fonts', 'Fonts', { difficulty: 'junior', reading: 25, tags: ['nextjs', 'performance'] }),
      t('server-components', 'Server Components', { difficulty: 'mid', reading: 45, prerequisites: ['10-react.server-components-overview'], tags: ['nextjs', 'rsc', 'interview-frequent'] }),
      t('client-components', 'Client Components', { difficulty: 'junior', reading: 30, prerequisites: ['11-nextjs.server-components'], tags: ['nextjs', 'rsc'] }),
      t('server-actions', 'Server Actions', { difficulty: 'mid', reading: 40, tags: ['nextjs'] }),
      t('streaming', 'Streaming', { difficulty: 'mid', reading: 35, tags: ['nextjs', 'rendering'] }),
      t('caching', 'Caching', { difficulty: 'senior', reading: 50, prerequisites: ['02-internet.http-caching'], tags: ['nextjs', 'caching', 'interview-frequent'] }),
      t('partial-prerendering', 'Partial Prerendering', { difficulty: 'senior', reading: 40, tags: ['nextjs', 'rendering'] }),
      t('data-fetching', 'Data Fetching', { difficulty: 'mid', reading: 40, tags: ['nextjs'] }),
      t('route-groups', 'Route Groups', { difficulty: 'mid', reading: 20, tags: ['nextjs', 'routing'] }),
      t('intercepting-routes', 'Intercepting Routes', { difficulty: 'senior', reading: 30, tags: ['nextjs', 'routing'] }),
      t('parallel-routes', 'Parallel Routes', { difficulty: 'senior', reading: 30, tags: ['nextjs', 'routing'] }),
    ],
  },
  {
    id: '12-rendering',
    title: 'Rendering',
    description: 'CSR through PPR, hydration models, and caching layers',
    topics: [
      t('csr', 'Client-Side Rendering', { difficulty: 'junior', reading: 30, tags: ['rendering'] }),
      t('ssr', 'Server-Side Rendering', { difficulty: 'mid', reading: 40, tags: ['rendering', 'interview-frequent'] }),
      t('ssg', 'Static Site Generation', { difficulty: 'junior', reading: 30, tags: ['rendering'] }),
      t('isr', 'Incremental Static Regeneration', { difficulty: 'mid', reading: 30, tags: ['rendering', 'nextjs'] }),
      t('ppr', 'Partial Prerendering', { difficulty: 'senior', reading: 35, related: ['11-nextjs.partial-prerendering'], tags: ['rendering', 'nextjs'] }),
      t('streaming', 'Streaming', { difficulty: 'mid', reading: 35, tags: ['rendering'] }),
      t('hydration', 'Hydration', { difficulty: 'mid', reading: 40, tags: ['rendering', 'react', 'interview-frequent'] }),
      t('progressive-hydration', 'Progressive Hydration', { difficulty: 'senior', reading: 30, prerequisites: ['12-rendering.hydration'], tags: ['rendering'] }),
      t('resumability', 'Resumability', { difficulty: 'senior', reading: 35, tags: ['rendering'] }),
      t('edge-rendering', 'Edge Rendering', { difficulty: 'mid', reading: 30, tags: ['rendering', 'edge'] }),
      t('cdn', 'CDN', { difficulty: 'junior', reading: 25, related: ['02-internet.cdn-basics'], tags: ['caching', 'networking'] }),
      t('browser-cache', 'Browser Cache', { difficulty: 'junior', reading: 25, prerequisites: ['02-internet.http-caching'], tags: ['caching'] }),
      t('cache-control', 'Cache-Control', { difficulty: 'mid', reading: 30, prerequisites: ['02-internet.http-caching'], tags: ['caching', 'http'] }),
      t('etag', 'ETag', { difficulty: 'mid', reading: 25, prerequisites: ['02-internet.http-caching'], tags: ['caching', 'http'] }),
      t('stale-while-revalidate', 'Stale While Revalidate', { difficulty: 'mid', reading: 25, prerequisites: ['02-internet.http-caching'], tags: ['caching'] }),
      t('rendering-strategy-decision-tree', 'Rendering Strategy Decision Tree', { difficulty: 'mid', reading: 35, tags: ['rendering', 'architecture'] }),
    ],
  },
  {
    id: '13-performance',
    title: 'Performance',
    description: 'Bundles, runtime techniques, and Core Web Vitals',
    topics: [
      t('bundle', 'Bundle', { difficulty: 'junior', reading: 25, tags: ['performance', 'bundling'] }),
      t('chunk', 'Chunk', { difficulty: 'junior', reading: 20, prerequisites: ['13-performance.bundle'], tags: ['performance', 'bundling'] }),
      t('bundling', 'Bundling', { difficulty: 'junior', reading: 30, tags: ['performance', 'bundling'] }),
      t('code-splitting', 'Code Splitting', { difficulty: 'mid', reading: 35, tags: ['performance', 'bundling'] }),
      t('tree-shaking', 'Tree Shaking', { difficulty: 'mid', reading: 30, tags: ['performance', 'bundling'] }),
      t('dead-code-elimination', 'Dead Code Elimination', { difficulty: 'mid', reading: 25, tags: ['performance', 'bundling'] }),
      t('dynamic-import', 'Dynamic Import', { difficulty: 'junior', reading: 25, tags: ['performance', 'javascript'] }),
      t('lazy-loading', 'Lazy Loading', { difficulty: 'junior', reading: 25, tags: ['performance'] }),
      t('debounce', 'Debounce', { difficulty: 'junior', reading: 20, tags: ['performance', 'javascript'] }),
      t('throttle', 'Throttle', { difficulty: 'junior', reading: 20, tags: ['performance', 'javascript'] }),
      t('memoization-perf', 'Memoization', { difficulty: 'junior', reading: 25, tags: ['performance'] }),
      t('virtualization', 'Virtualization', { difficulty: 'mid', reading: 35, tags: ['performance', 'react'] }),
      t('image-optimization-perf', 'Image Optimization', { difficulty: 'junior', reading: 30, tags: ['performance'] }),
      t('font-performance', 'Font Performance', { difficulty: 'mid', reading: 25, tags: ['performance'] }),
      t('lighthouse', 'Lighthouse', { difficulty: 'junior', reading: 30, tags: ['performance', 'devtools'] }),
      t('core-web-vitals', 'Core Web Vitals', { difficulty: 'mid', reading: 35, tags: ['performance', 'interview-frequent'] }),
      t('lcp', 'LCP', { difficulty: 'mid', reading: 30, prerequisites: ['13-performance.core-web-vitals'], tags: ['performance'] }),
      t('cls', 'CLS', { difficulty: 'mid', reading: 30, prerequisites: ['13-performance.core-web-vitals'], tags: ['performance'] }),
      t('inp', 'INP', { difficulty: 'mid', reading: 30, prerequisites: ['13-performance.core-web-vitals'], tags: ['performance'] }),
      t('ttfb', 'TTFB', { difficulty: 'mid', reading: 20, tags: ['performance', 'networking'] }),
      t('tti', 'TTI', { difficulty: 'mid', reading: 20, tags: ['performance'] }),
      t('fcp', 'FCP', { difficulty: 'mid', reading: 20, tags: ['performance'] }),
      t('tbt', 'TBT', { difficulty: 'mid', reading: 20, tags: ['performance'] }),
      t('profiling', 'Profiling', { difficulty: 'mid', reading: 35, tags: ['performance', 'devtools'] }),
      t('long-tasks', 'Long Tasks', { difficulty: 'mid', reading: 30, tags: ['performance'] }),
      t('scheduler-yielding', 'Scheduler and Yielding', { difficulty: 'senior', reading: 35, tags: ['performance'] }),
    ],
  },
  {
    id: '14-build-tools',
    title: 'Build Tools',
    description: 'Runtimes, package managers, bundlers, and compilers',
    topics: [
      t('nodejs', 'Node.js', { difficulty: 'junior', reading: 35, tags: ['nodejs', 'tooling'] }),
      t('npm', 'npm', { difficulty: 'beginner', reading: 25, tags: ['tooling'] }),
      t('pnpm', 'pnpm', { difficulty: 'junior', reading: 25, tags: ['tooling'] }),
      t('yarn', 'Yarn', { difficulty: 'junior', reading: 20, tags: ['tooling'] }),
      t('bun', 'Bun', { difficulty: 'mid', reading: 25, tags: ['tooling'] }),
      t('module-resolution', 'Module Resolution', { difficulty: 'mid', reading: 40, prerequisites: ['06-javascript.es-modules'], tags: ['tooling', 'javascript'] }),
      t('webpack', 'Webpack', { difficulty: 'mid', reading: 40, tags: ['bundling', 'tooling'] }),
      t('rollup', 'Rollup', { difficulty: 'mid', reading: 30, tags: ['bundling', 'tooling'] }),
      t('vite', 'Vite', { difficulty: 'junior', reading: 35, tags: ['bundling', 'tooling'] }),
      t('turbopack', 'Turbopack', { difficulty: 'mid', reading: 25, tags: ['bundling', 'tooling', 'nextjs'] }),
      t('rspack', 'Rspack', { difficulty: 'mid', reading: 25, tags: ['bundling', 'tooling'] }),
      t('parcel', 'Parcel', { difficulty: 'mid', reading: 20, tags: ['bundling', 'tooling'] }),
      t('babel', 'Babel', { difficulty: 'mid', reading: 30, related: ['08-jsx-and-react-runtime.babel'], tags: ['compilers', 'tooling'] }),
      t('swc', 'SWC', { difficulty: 'mid', reading: 25, tags: ['compilers', 'tooling'] }),
      t('esbuild', 'esbuild', { difficulty: 'mid', reading: 25, tags: ['compilers', 'tooling'] }),
      t('postcss', 'PostCSS', { difficulty: 'junior', reading: 25, tags: ['css', 'tooling'] }),
      t('source-maps', 'Source Maps', { difficulty: 'mid', reading: 30, tags: ['tooling', 'devtools'] }),
      t('monorepo-tooling', 'Monorepo Tooling', { difficulty: 'mid', reading: 35, related: ['15-architecture.monorepo'], tags: ['tooling', 'architecture'] }),
    ],
  },
  {
    id: '15-architecture',
    title: 'Architecture',
    description: 'Application structure, state, design systems, monorepos, and micro frontends',
    topics: [
      t('feature-based-architecture', 'Feature-Based Architecture', { difficulty: 'mid', reading: 35, tags: ['architecture'] }),
      t('atomic-design', 'Atomic Design', { difficulty: 'junior', reading: 25, tags: ['architecture', 'design-systems'] }),
      t('design-systems', 'Design Systems', { difficulty: 'mid', reading: 40, tags: ['architecture', 'design-systems'] }),
      t('monorepo', 'Monorepo', { difficulty: 'mid', reading: 40, tags: ['architecture'] }),
      t('micro-frontends', 'Micro Frontends', { difficulty: 'senior', reading: 45, tags: ['architecture'] }),
      t('module-federation', 'Module Federation', { difficulty: 'senior', reading: 40, prerequisites: ['15-architecture.micro-frontends'], tags: ['architecture', 'bundling'] }),
      t('state-management', 'State Management', { difficulty: 'mid', reading: 35, tags: ['architecture', 'state'] }),
      t('redux', 'Redux', { difficulty: 'mid', reading: 40, prerequisites: ['15-architecture.state-management'], tags: ['state', 'react'] }),
      t('zustand', 'Zustand', { difficulty: 'junior', reading: 25, prerequisites: ['15-architecture.state-management'], tags: ['state', 'react'] }),
      t('jotai', 'Jotai', { difficulty: 'mid', reading: 25, prerequisites: ['15-architecture.state-management'], tags: ['state', 'react'] }),
      t('tanstack-query', 'TanStack Query', { difficulty: 'mid', reading: 40, tags: ['state', 'data-fetching', 'react'] }),
      t('react-router', 'React Router', { difficulty: 'junior', reading: 35, tags: ['routing', 'react'] }),
      t('url-as-state', 'URL as State', { difficulty: 'mid', reading: 30, tags: ['routing', 'architecture'] }),
      t('component-libraries', 'Component Libraries', { difficulty: 'mid', reading: 30, tags: ['architecture', 'design-systems'] }),
      t('api-layer-design', 'API Layer Design', { difficulty: 'mid', reading: 35, tags: ['architecture', 'api'] }),
      t('error-handling-architecture', 'Error Handling Architecture', { difficulty: 'mid', reading: 30, tags: ['architecture'] }),
    ],
  },
  {
    id: '16-testing',
    title: 'Testing',
    description: 'Test pyramid and frontend testing tooling',
    topics: [
      t('testing-pyramid', 'Testing Pyramid', { difficulty: 'junior', reading: 25, tags: ['testing'] }),
      t('unit-testing', 'Unit Testing', { difficulty: 'junior', reading: 30, tags: ['testing'] }),
      t('integration-testing', 'Integration Testing', { difficulty: 'mid', reading: 30, tags: ['testing'] }),
      t('e2e-testing', 'E2E Testing', { difficulty: 'mid', reading: 30, tags: ['testing'] }),
      t('jest', 'Jest', { difficulty: 'junior', reading: 30, tags: ['testing'] }),
      t('vitest', 'Vitest', { difficulty: 'junior', reading: 30, tags: ['testing'] }),
      t('react-testing-library', 'React Testing Library', { difficulty: 'junior', reading: 35, tags: ['testing', 'react'] }),
      t('cypress', 'Cypress', { difficulty: 'mid', reading: 30, tags: ['testing', 'e2e'] }),
      t('playwright', 'Playwright', { difficulty: 'mid', reading: 35, tags: ['testing', 'e2e'] }),
      t('mocking', 'Mocking', { difficulty: 'junior', reading: 25, tags: ['testing'] }),
      t('spying', 'Spying', { difficulty: 'junior', reading: 20, tags: ['testing'] }),
      t('msw', 'MSW', { difficulty: 'mid', reading: 30, tags: ['testing', 'api'] }),
      t('visual-regression', 'Visual Regression', { difficulty: 'mid', reading: 25, tags: ['testing'] }),
      t('accessibility-testing', 'Accessibility Testing', { difficulty: 'mid', reading: 25, related: ['18-accessibility.a11y-testing'], tags: ['testing', 'a11y'] }),
      t('test-strategy', 'Test Strategy', { difficulty: 'mid', reading: 30, tags: ['testing', 'architecture'] }),
    ],
  },
  {
    id: '17-security',
    title: 'Security',
    description: 'Frontend threat model, browser security controls, and auth tokens',
    topics: [
      t('threat-model', 'Threat Model', { difficulty: 'mid', reading: 30, tags: ['security'] }),
      t('xss', 'XSS', { difficulty: 'mid', reading: 40, tags: ['security', 'interview-frequent'] }),
      t('csrf', 'CSRF', { difficulty: 'mid', reading: 35, tags: ['security', 'interview-frequent'] }),
      t('cors', 'CORS', { difficulty: 'mid', reading: 40, prerequisites: ['02-internet.http'], tags: ['security', 'networking', 'interview-frequent'] }),
      t('csp', 'Content Security Policy', { difficulty: 'mid', reading: 35, tags: ['security'] }),
      t('jwt', 'JWT', { difficulty: 'mid', reading: 35, tags: ['security', 'auth'] }),
      t('oauth', 'OAuth', { difficulty: 'mid', reading: 40, tags: ['security', 'auth'] }),
      t('oidc', 'OIDC', { difficulty: 'mid', reading: 30, prerequisites: ['17-security.oauth'], tags: ['security', 'auth'] }),
      t('cookies-security', 'Cookies Security', { difficulty: 'mid', reading: 30, prerequisites: ['02-internet.cookies'], tags: ['security'] }),
      t('samesite', 'SameSite', { difficulty: 'mid', reading: 25, prerequisites: ['17-security.cookies-security'], tags: ['security'] }),
      t('secure-cookies', 'Secure Cookies', { difficulty: 'mid', reading: 20, prerequisites: ['17-security.cookies-security'], tags: ['security'] }),
      t('https-security', 'HTTPS Security', { difficulty: 'junior', reading: 25, prerequisites: ['02-internet.https'], tags: ['security'] }),
      t('clickjacking', 'Clickjacking', { difficulty: 'mid', reading: 20, tags: ['security'] }),
      t('prototype-pollution', 'Prototype Pollution', { difficulty: 'senior', reading: 30, prerequisites: ['06-javascript.prototype'], tags: ['security', 'javascript'] }),
      t('supply-chain-security', 'Supply Chain Security', { difficulty: 'mid', reading: 30, tags: ['security', 'tooling'] }),
      t('secrets-in-frontend', 'Secrets in the Frontend', { difficulty: 'junior', reading: 20, tags: ['security'] }),
    ],
  },
  {
    id: '18-accessibility',
    title: 'Accessibility',
    description: 'WCAG, ARIA, keyboard UX, and accessible component patterns',
    topics: [
      t('why-accessibility', 'Why Accessibility', { difficulty: 'beginner', reading: 20, tags: ['a11y'] }),
      t('wcag', 'WCAG', { difficulty: 'junior', reading: 35, tags: ['a11y'] }),
      t('aria', 'ARIA', { difficulty: 'mid', reading: 40, prerequisites: ['18-accessibility.wcag'], tags: ['a11y', 'interview-frequent'] }),
      t('semantic-html-a11y', 'Semantic HTML for Accessibility', { difficulty: 'beginner', reading: 25, prerequisites: ['04-html.semantic-html'], tags: ['a11y', 'html'] }),
      t('keyboard-navigation', 'Keyboard Navigation', { difficulty: 'junior', reading: 30, tags: ['a11y'] }),
      t('focus-management', 'Focus Management', { difficulty: 'mid', reading: 30, tags: ['a11y'] }),
      t('screen-readers', 'Screen Readers', { difficulty: 'mid', reading: 35, tags: ['a11y'] }),
      t('color-and-contrast', 'Color and Contrast', { difficulty: 'junior', reading: 25, tags: ['a11y', 'css'] }),
      t('forms-a11y', 'Accessible Forms', { difficulty: 'junior', reading: 30, prerequisites: ['04-html.forms'], tags: ['a11y', 'html'] }),
      t('live-regions', 'Live Regions', { difficulty: 'mid', reading: 25, tags: ['a11y'] }),
      t('accessible-components', 'Accessible Components', { difficulty: 'mid', reading: 40, tags: ['a11y', 'react'] }),
      t('a11y-testing', 'Accessibility Testing', { difficulty: 'mid', reading: 30, tags: ['a11y', 'testing'] }),
      t('a11y-in-react', 'Accessibility in React', { difficulty: 'mid', reading: 30, tags: ['a11y', 'react'] }),
      t('a11y-in-nextjs', 'Accessibility in Next.js', { difficulty: 'mid', reading: 25, tags: ['a11y', 'nextjs'] }),
    ],
  },
  {
    id: '19-deployment',
    title: 'Deployment',
    description: 'Containers, proxies, CDNs, CI/CD, and hosting platforms',
    topics: [
      t('docker', 'Docker', { difficulty: 'mid', reading: 40, tags: ['deployment'] }),
      t('nginx', 'Nginx', { difficulty: 'mid', reading: 35, tags: ['deployment', 'networking'] }),
      t('reverse-proxy', 'Reverse Proxy', { difficulty: 'mid', reading: 30, tags: ['deployment', 'networking'] }),
      t('cdn-deployment', 'CDN Deployment', { difficulty: 'junior', reading: 25, tags: ['deployment', 'caching'] }),
      t('ci-cd', 'CI/CD', { difficulty: 'junior', reading: 30, tags: ['deployment'] }),
      t('github-actions', 'GitHub Actions', { difficulty: 'junior', reading: 35, prerequisites: ['19-deployment.ci-cd'], tags: ['deployment'] }),
      t('vercel', 'Vercel', { difficulty: 'junior', reading: 25, tags: ['deployment', 'nextjs'] }),
      t('netlify', 'Netlify', { difficulty: 'junior', reading: 20, tags: ['deployment'] }),
      t('aws-frontend', 'AWS for Frontend', { difficulty: 'mid', reading: 40, tags: ['deployment'] }),
      t('cloudflare', 'Cloudflare', { difficulty: 'mid', reading: 35, tags: ['deployment', 'edge'] }),
      t('environment-config', 'Environment Config', { difficulty: 'junior', reading: 25, tags: ['deployment', 'security'] }),
      t('preview-deployments', 'Preview Deployments', { difficulty: 'junior', reading: 20, tags: ['deployment'] }),
      t('rollback-strategies', 'Rollback Strategies', { difficulty: 'mid', reading: 25, tags: ['deployment'] }),
    ],
  },
  {
    id: '20-observability',
    title: 'Observability',
    description: 'DevTools, debugging, RUM, logging, and frontend telemetry',
    topics: [
      t('chrome-devtools', 'Chrome DevTools', { difficulty: 'junior', reading: 40, tags: ['devtools', 'observability'] }),
      t('debugging-javascript', 'Debugging JavaScript', { difficulty: 'junior', reading: 30, tags: ['devtools', 'javascript'] }),
      t('debugging-network', 'Debugging Network', { difficulty: 'junior', reading: 30, tags: ['devtools', 'networking'] }),
      t('debugging-performance', 'Debugging Performance', { difficulty: 'mid', reading: 35, tags: ['devtools', 'performance'] }),
      t('source-maps-debugging', 'Source Maps Debugging', { difficulty: 'mid', reading: 25, related: ['14-build-tools.source-maps'], tags: ['devtools'] }),
      t('logging', 'Logging', { difficulty: 'junior', reading: 25, tags: ['observability'] }),
      t('error-tracking', 'Error Tracking', { difficulty: 'mid', reading: 30, tags: ['observability'] }),
      t('rum', 'Real User Monitoring', { difficulty: 'mid', reading: 30, tags: ['observability', 'performance'] }),
      t('web-vitals-monitoring', 'Web Vitals Monitoring', { difficulty: 'mid', reading: 25, prerequisites: ['13-performance.core-web-vitals'], tags: ['observability', 'performance'] }),
      t('tracing-frontend', 'Frontend Tracing', { difficulty: 'senior', reading: 30, tags: ['observability'] }),
      t('feature-telemetry', 'Feature Telemetry', { difficulty: 'mid', reading: 25, tags: ['observability'] }),
    ],
  },
  {
    id: '21-frontend-system-design',
    title: 'Frontend System Design',
    description: 'Product-scale frontend design problems and trade-offs',
    topics: [
      t('scaling-react-applications', 'Scaling React Applications', { difficulty: 'senior', reading: 45, tags: ['system-design', 'react'] }),
      t('caching-strategies', 'Caching Strategies', { difficulty: 'mid', reading: 40, tags: ['system-design', 'caching'] }),
      t('optimistic-ui', 'Optimistic UI', { difficulty: 'mid', reading: 30, tags: ['system-design', 'ux'] }),
      t('offline-first', 'Offline First', { difficulty: 'mid', reading: 30, related: ['23-pwa-and-offline.pwa-overview'], tags: ['system-design', 'pwa'] }),
      t('infinite-scroll', 'Infinite Scroll', { difficulty: 'mid', reading: 30, tags: ['system-design', 'ux'] }),
      t('pagination', 'Pagination', { difficulty: 'junior', reading: 25, tags: ['system-design', 'api'] }),
      t('feature-flags', 'Feature Flags', { difficulty: 'mid', reading: 30, tags: ['system-design'] }),
      t('realtime-applications', 'Realtime Applications', { difficulty: 'senior', reading: 40, prerequisites: ['02-internet.websocket'], tags: ['system-design', 'realtime'] }),
      t('search-ui', 'Search UI', { difficulty: 'mid', reading: 30, tags: ['system-design'] }),
      t('upload-pipelines', 'Upload Pipelines', { difficulty: 'mid', reading: 30, tags: ['system-design'] }),
      t('multi-tenant-ui', 'Multi-Tenant UI', { difficulty: 'senior', reading: 35, tags: ['system-design'] }),
      t('internationalized-apps', 'Internationalized Apps', { difficulty: 'mid', reading: 35, tags: ['system-design', 'i18n'] }),
      t('designing-design-systems', 'Designing Design Systems', { difficulty: 'senior', reading: 40, related: ['15-architecture.design-systems'], tags: ['system-design', 'design-systems'] }),
    ],
  },
  {
    id: '22-design-patterns',
    title: 'Design Patterns',
    description: 'Patterns used in frontend codebases — and when they hurt',
    topics: [
      t('mvc-mvp-mvvm', 'MVC, MVP, MVVM', { difficulty: 'mid', reading: 30, tags: ['patterns'] }),
      t('container-presentational', 'Container / Presentational', { difficulty: 'junior', reading: 25, tags: ['patterns', 'react'] }),
      t('hooks-patterns', 'Hooks Patterns', { difficulty: 'mid', reading: 30, tags: ['patterns', 'react'] }),
      t('compound-components', 'Compound Components', { difficulty: 'mid', reading: 30, tags: ['patterns', 'react'] }),
      t('render-props', 'Render Props', { difficulty: 'mid', reading: 25, tags: ['patterns', 'react'] }),
      t('hoc', 'Higher-Order Components', { difficulty: 'mid', reading: 25, tags: ['patterns', 'react'] }),
      t('provider-pattern', 'Provider Pattern', { difficulty: 'junior', reading: 25, tags: ['patterns', 'react'] }),
      t('observer-pattern', 'Observer Pattern', { difficulty: 'mid', reading: 25, tags: ['patterns'] }),
      t('module-pattern', 'Module Pattern', { difficulty: 'junior', reading: 20, tags: ['patterns', 'javascript'] }),
      t('factory-and-builder', 'Factory and Builder', { difficulty: 'mid', reading: 25, tags: ['patterns'] }),
      t('when-patterns-hurt', 'When Patterns Hurt', { difficulty: 'mid', reading: 25, tags: ['patterns', 'architecture'] }),
    ],
  },
  {
    id: '23-pwa-and-offline',
    title: 'PWA and Offline',
    description: 'Service workers, caching strategies, and offline UX',
    topics: [
      t('pwa-overview', 'PWA Overview', { difficulty: 'junior', reading: 25, tags: ['pwa'] }),
      t('service-worker-lifecycle', 'Service Worker Lifecycle', { difficulty: 'mid', reading: 40, prerequisites: ['09-browser-apis.service-workers'], tags: ['pwa'] }),
      t('caching-strategies-sw', 'Service Worker Caching Strategies', { difficulty: 'mid', reading: 40, prerequisites: ['23-pwa-and-offline.service-worker-lifecycle'], tags: ['pwa', 'caching'] }),
      t('background-sync', 'Background Sync', { difficulty: 'senior', reading: 25, tags: ['pwa'] }),
      t('web-app-manifest', 'Web App Manifest', { difficulty: 'junior', reading: 20, tags: ['pwa'] }),
      t('installability', 'Installability', { difficulty: 'junior', reading: 20, tags: ['pwa'] }),
      t('push-notifications', 'Push Notifications', { difficulty: 'mid', reading: 30, tags: ['pwa'] }),
      t('offline-ux', 'Offline UX', { difficulty: 'mid', reading: 25, tags: ['pwa', 'ux'] }),
    ],
  },
  {
    id: '24-interview-preparation',
    title: 'Interview Preparation',
    description: 'Question banks with deep answers linked to canonical topics',
    topics: [
      t('how-to-answer', 'How to Answer', { difficulty: 'junior', reading: 20, tags: ['interview'] }),
      t('javascript-interview-questions', 'JavaScript Interview Questions', { difficulty: 'mid', reading: 60, tags: ['interview', 'javascript'] }),
      t('browser-interview-questions', 'Browser Interview Questions', { difficulty: 'mid', reading: 60, tags: ['interview', 'browser-internals'] }),
      t('react-interview-questions', 'React Interview Questions', { difficulty: 'mid', reading: 60, tags: ['interview', 'react'] }),
      t('nextjs-interview-questions', 'Next.js Interview Questions', { difficulty: 'mid', reading: 45, tags: ['interview', 'nextjs'] }),
      t('network-interview-questions', 'Network Interview Questions', { difficulty: 'mid', reading: 45, tags: ['interview', 'networking'] }),
      t('css-interview-questions', 'CSS Interview Questions', { difficulty: 'mid', reading: 45, tags: ['interview', 'css'] }),
      t('typescript-interview-questions', 'TypeScript Interview Questions', { difficulty: 'mid', reading: 45, tags: ['interview', 'typescript'] }),
      t('performance-interview-questions', 'Performance Interview Questions', { difficulty: 'mid', reading: 45, tags: ['interview', 'performance'] }),
      t('security-interview-questions', 'Security Interview Questions', { difficulty: 'mid', reading: 40, tags: ['interview', 'security'] }),
      t('system-design-interview-questions', 'System Design Interview Questions', { difficulty: 'senior', reading: 60, tags: ['interview', 'system-design'] }),
    ],
  },
  {
    id: '25-appendix',
    title: 'Appendix',
    description: 'Cheatsheets, compatibility tables, and curriculum changelog',
    topics: [
      t('browser-compatibility', 'Browser Compatibility', { difficulty: 'junior', reading: 20, tags: ['appendix'] }),
      t('http-status-codes', 'HTTP Status Codes', { difficulty: 'beginner', reading: 15, tags: ['appendix', 'http'] }),
      t('mime-types', 'MIME Types', { difficulty: 'beginner', reading: 10, tags: ['appendix'] }),
      t('priority-hints-cheatsheet', 'Priority Hints Cheatsheet', { difficulty: 'mid', reading: 15, tags: ['appendix', 'performance'] }),
      t('glossary-export', 'Glossary Export', { difficulty: 'beginner', reading: 10, tags: ['appendix'] }),
      t('curriculum-changelog', 'Curriculum Changelog', { difficulty: 'beginner', reading: 10, tags: ['appendix'] }),
      t('further-reading-policy', 'Further Reading Policy', { difficulty: 'beginner', reading: 10, tags: ['appendix'] }),
    ],
  },
]
