import fs from 'node:fs'
import path from 'node:path'
import YAML from 'yaml'
import { loadRegistry } from './lib/load-registry.js'
import { KG_OVERVIEW_MD, KNOWLEDGE_GRAPH_PATH } from './lib/paths.js'

const registry = loadRegistry()

const moduleNodes = registry.modules
  .map((m) => `  ${m.id.replace(/-/g, '_')}["${m.title}"]`)
  .join('\n')

const moduleEdges = [
  '  foundations_00[00_Foundations] --> computer_science_01[01_ComputerScience]',
  '  computer_science_01 --> internet_02[02_Internet]',
  '  internet_02 --> browser_03[03_Browser]',
  '  browser_03 --> html_04[04_HTML]',
  '  html_04 --> css_05[05_CSS]',
  '  browser_03 --> javascript_06[06_JavaScript]',
  '  javascript_06 --> typescript_07[07_TypeScript]',
  '  javascript_06 --> jsx_08[08_JSX_Fiber]',
  '  jsx_08 --> react_10[10_React]',
  '  browser_03 --> browser_apis_09[09_BrowserAPIs]',
  '  html_04 --> accessibility_18[18_Accessibility]',
  '  css_05 --> accessibility_18',
  '  react_10 --> nextjs_11[11_Nextjs]',
  '  react_10 --> rendering_12[12_Rendering]',
  '  nextjs_11 --> rendering_12',
  '  javascript_06 --> build_tools_14[14_BuildTools]',
  '  build_tools_14 --> performance_13[13_Performance]',
  '  rendering_12 --> performance_13',
  '  react_10 --> architecture_15[15_Architecture]',
  '  react_10 --> patterns_22[22_DesignPatterns]',
  '  browser_apis_09 --> pwa_23[23_PWA]',
  '  architecture_15 --> system_design_21[21_SystemDesign]',
  '  nextjs_11 --> deployment_19[19_Deployment]',
  '  performance_13 --> observability_20[20_Observability]',
  '  security_17[17_Security] --> deployment_19',
  '  testing_16[16_Testing] --> system_design_21',
  '  system_design_21 --> interview_24[24_Interview]',
].join('\n')

const md = `---
title: Knowledge Graph Overview
description: Generated module-level dependency map for the handbook curriculum
omit_sections: true
---

# Knowledge Graph Overview

::: info Generated
This page is generated by \`pnpm registry:knowledge-graph\`. Edit edges via \`meta/topic-registry.yaml\` / \`scripts/seed-meta.ts\`.
:::

## Module dependencies

\`\`\`mermaid
flowchart TB
${moduleEdges}
\`\`\`

## Modules

\`\`\`mermaid
flowchart LR
${moduleNodes}
\`\`\`

## Stats

| Metric | Value |
| --- | --- |
| Modules | ${registry.modules.length} |
| Topics | ${registry.topics.length} |
| Stub topics | ${registry.topics.filter((t) => t.status === 'stub').length} |

## Edge dump

Machine-readable edges: [\`meta/knowledge-graph.yaml\`](../../../meta/knowledge-graph.yaml).
`

fs.mkdirSync(path.dirname(KG_OVERVIEW_MD), { recursive: true })
fs.writeFileSync(KG_OVERVIEW_MD, md, 'utf8')

// Refresh edge dump from registry if missing
if (!fs.existsSync(KNOWLEDGE_GRAPH_PATH)) {
  const edges = registry.topics.flatMap((topic) => {
    const out: { from: string; to: string; type: string }[] = []
    for (const to of topic.depends_on) out.push({ from: topic.id, to, type: 'depends_on' })
    for (const to of topic.related) out.push({ from: topic.id, to, type: 'related_to' })
    for (const to of topic.children) out.push({ from: topic.id, to, type: 'child_of' })
    for (const to of topic.perspective_of) out.push({ from: topic.id, to, type: 'perspective_of' })
    for (const to of topic.advanced) out.push({ from: topic.id, to, type: 'deepens' })
    return out
  })
  fs.writeFileSync(
    KNOWLEDGE_GRAPH_PATH,
    YAML.stringify({
      version: 1,
      edge_types: ['depends_on', 'child_of', 'related_to', 'deepens', 'perspective_of'],
      edges,
    }),
    'utf8',
  )
}

console.log(`Wrote ${KG_OVERVIEW_MD}`)
