import fs from 'node:fs'
import path from 'node:path'
import { loadRegistry } from './lib/load-registry.js'
import { SIDEBARS_DIR, topicHref } from './lib/paths.js'

type VPItem = { text: string; link?: string; collapsed?: boolean; items?: VPItem[] }

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true })
}

const registry = loadRegistry()
ensureDir(SIDEBARS_DIR)

const moduleFiles: string[] = []

for (const mod of [...registry.modules].sort((a, b) => a.order - b.order)) {
  const topics = registry.topics
    .filter((t) => t.module === mod.id)
    .sort((a, b) => a.order - b.order)

  const roots = topics.filter((t) => t.parents.length === 1 && t.parents[0] === mod.id)
  const byParent = new Map<string, typeof topics>()
  for (const topic of topics) {
    for (const parent of topic.parents) {
      if (parent === mod.id) continue
      const list = byParent.get(parent) ?? []
      list.push(topic)
      byParent.set(parent, list)
    }
  }

  function toItem(topicId: string, seen = new Set<string>()): VPItem | null {
    if (seen.has(topicId)) return null
    seen.add(topicId)
    const topic = topics.find((t) => t.id === topicId)
    if (!topic) return null
    const children = (byParent.get(topic.id) ?? []).sort((a, b) => a.order - b.order)
    if (children.length) {
      return {
        text: topic.title,
        collapsed: true,
        items: [
          { text: 'Overview', link: topicHref(topic.path) },
          ...children.map((c) => toItem(c.id, seen)).filter(Boolean) as VPItem[],
        ],
      }
    }
    return { text: topic.title, link: topicHref(topic.path) }
  }

  const items: VPItem[] = [
    { text: 'Module overview', link: `/${mod.id}/` },
    ...roots.map((r) => toItem(r.id)).filter(Boolean) as VPItem[],
  ]

  const fileBase = mod.id
  const filePath = path.join(SIDEBARS_DIR, `${fileBase}.ts`)
  const content = `import type { DefaultTheme } from 'vitepress'

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebar: DefaultTheme.SidebarItem[] = ${JSON.stringify(items, null, 2)}
`
  fs.writeFileSync(filePath, content, 'utf8')
  moduleFiles.push(fileBase)
  console.log(`Wrote ${filePath}`)
}

const indexContent = `import type { DefaultTheme } from 'vitepress'
${moduleFiles.map((id) => `import { sidebar as sidebar_${id.replace(/-/g, '_')} } from './${id}.js'`).join('\n')}

// AUTO-GENERATED by scripts/generate-sidebars.ts — do not edit by hand
export const sidebars: DefaultTheme.Sidebar = {
${moduleFiles
  .map((id) => {
    const key = `/${id}/`
    const varName = `sidebar_${id.replace(/-/g, '_')}`
    return `  '${key}': ${varName},`
  })
  .join('\n')}
}
`
fs.writeFileSync(path.join(SIDEBARS_DIR, 'index.ts'), indexContent, 'utf8')
console.log(`Wrote ${path.join(SIDEBARS_DIR, 'index.ts')}`)
