import fs from 'node:fs'
import path from 'node:path'
import { loadRegistry } from './lib/load-registry.js'
import { ROOT, topicHref } from './lib/paths.js'

const registry = loadRegistry()
const map: Record<string, { href: string; title: string }> = {}
for (const topic of registry.topics) {
  map[topic.id] = { href: topicHref(topic.path), title: topic.title }
}

const out = path.join(ROOT, 'docs', '.vitepress', 'topic-map.ts')
const body = `// AUTO-GENERATED by scripts/generate-topic-map.ts — do not edit by hand
export const topicMap: Record<string, { href: string; title: string }> = ${JSON.stringify(map, null, 2)}

export function topicHrefById(id: string): string {
  return topicMap[id]?.href ?? \`#missing-topic-\${id}\`
}

export function topicTitleById(id: string): string {
  return topicMap[id]?.title ?? id
}
`
fs.writeFileSync(out, body, 'utf8')
console.log(`Wrote ${out} (${Object.keys(map).length} topics)`)
